// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The runtime connection is made via the pg driver adapter in
    // src/utils/db.ts using process.env.DATABASE_URL. This url is only used by
    // Prisma CLI commands (migrate/db push); fall back to a placeholder so
    // `prisma generate` and `pnpm install` succeed without DATABASE_URL set.
    url: process.env.DATABASE_URL ?? "postgresql://placeholder",
  },
});
