export const headers: Record<string, string[]> = {
  defensive_assist: [
    "event_type",
    "Match Time",
    "Player Team",
    "Player Name",
    "Player Hero",
    "Hero Duplicated",
  ],
  dva_remech: [
    "event_type",
    "Match Time",
    "Player Team",
    "Player Name",
    "Player Hero",
    "Hero Duplicated",
  ],
  echo_duplicate_end: [
    "event_type",
    "Match Time",
    "Player Team",
    "Player Name",
    "Player Hero",
    "Ultimate ID",
  ],
  echo_duplicate_start: [
    "event_type",
    "Match Time",
    "Player Team",
    "Player Name",
    "Player Hero",
    "Hero Duplicated",
    "Ultimate ID",
  ],
  hero_spawn: [
    "event_type",
    "Match Time",
    "Player Team",
    "Player Name",
    "Player Hero",
    "Previous Hero",
    "Hero Time Played",
  ],
  hero_swap: [
    "event_type",
    "Match Time",
    "Player Team",
    "Player Name",
    "Player Hero",
    "Previous Hero",
    "Hero Time Played",
  ],
  kill: [
    "event_type",
    "Match Time",
    "Attacker Team",
    "Attacker Name",
    "Attacker Hero",
    "Victim Team",
    "Victim Name",
    "Victim Hero",
    "Event Ability",
    "Event Damage",
    "Is Critical Hit",
    "Is Environmental",
  ],
  match_end: [
    "event_type",
    "Match Time",
    "Round Number",
    "Team 1 Score",
    "Team 2 Score",
  ],
  match_start: [
    "event_type",
    "Match Time",
    "Map Name",
    "Map Type",
    "Team 1 Name",
    "Team 2 Name",
  ],
  mercy_rez: [
    "event_type",
    "Match Time",
    "Resurrecter Team",
    "Resurrecter Player",
    "Resurrecter Hero",
    "Resurrectee Team",
    "Resurrectee Player",
    "Resurrectee Hero",
  ],
  objective_captured: [
    "event_type",
    "Match Time",
    "Round Number",
    "Capturing Team",
    "Objective Index",
    "Control Team 1 Progress",
    "Control Team 2 Progress",
    "Match Time Remaining",
  ],
  objective_updated: [
    "event_type",
    "Match Time",
    "Round Number",
    "Previous Objective",
    "Current Objective Index",
  ],
  offensive_assist: [
    "event_type",
    "Match Time",
    "Player Team",
    "Player Name",
    "Player Hero",
    "Hero Duplicated",
  ],
  payload_progress: [
    "event_type",
    "Match Time",
    "Round Number",
    "Capturing Team",
    "Objective Index",
    "Payload Capture Progress",
  ],
  player_stat: [
    "event_type",
    "Match Time",
    "Round Number",
    "Player Team",
    "Player Name",
    "Player Hero",
    "Eliminations",
    "Final Blows",
    "Deaths",
    "All Damage Dealt",
    "Barrier Damage Dealt",
    "Hero Damage Dealt",
    "Healing Dealt",
    "Healing Received",
    "Self Healing",
    "Damage Taken",
    "Damage Blocked",
    "Defensive Assists",
    "Offensive Assists",
    "Ultimates Earned",
    "Ultimates Used",
    "Multikill Best",
    "Multikills",
    "Solo Kills",
    "Objective Kills",
    "Environmental Kills",
    "Environmental Deaths",
    "Critical Hits",
    "Critical Hit Accuracy",
    "Scoped Accuracy",
    "Scoped Critical Hit Accuracy",
    "Scoped Critical Hit Kills",
    "Shots Fired",
    "Shots Hit",
    "Shots Missed",
    "Scoped Shots",
    "Weapon Accuracy",
    "Hero Time Played",
  ],
  point_progress: [
    "event_type",
    "Match Time",
    "Round Number",
    "Capturing Team",
    "Objective Index",
    "Point Capture Progress",
  ],
  remech_charged: [
    "event_type",
    "Match Time",
    "Player Team",
    "Player Name",
    "Player Hero",
    "Hero Duplicated",
    "Ultimate ID",
  ],
  round_end: [
    "event_type",
    "Match Time",
    "Round Number",
    "Capturing Team",
    "Team 1 Score",
    "Team 2 Score",
    "Objective Index",
    "Control Team 1 Progress",
    "Control Team 2 Progress",
    "Match Time Remaining",
  ],
  round_start: [
    "event_type",
    "Match Time",
    "Round Number",
    "Capturing Team",
    "Team 1 Score",
    "Team 2 Score",
    "Objective Index",
  ],
  setup_complete: [
    "event_type",
    "Match Time",
    "Round Number",
    "Match Time Remaining",
  ],
  ultimate_charged: [
    "event_type",
    "Match Time",
    "Player Team",
    "Player Name",
    "Player Hero",
    "Hero Duplicated",
    "Ultimate ID",
  ],
  ultimate_end: [
    "event_type",
    "Match Time",
    "Player Team",
    "Player Name",
    "Player Hero",
    "Hero Duplicated",
    "Ultimate ID",
  ],
  ultimate_start: [
    "event_type",
    "Match Time",
    "Player Team",
    "Player Name",
    "Player Hero",
    "Hero Duplicated",
    "Ultimate ID",
  ],
};
