-- CreateEnum
CREATE TYPE "public"."AuditLogAction" AS ENUM ('USER_BAN', 'USER_UNBAN', 'TRUST_SCORE_ADJUST', 'IMPERSONATE_USER', 'SUSPICIOUS_ACTIVITY_DETECTED', 'TEAM_INVITE_SENT', 'TEAM_AVATAR_UPDATED', 'TEAM_JOINED', 'TEAM_LEFT', 'TEAM_CREATED', 'TEAM_DELETED', 'TEAM_UPDATED', 'TEAM_MEMBER_PROMOTED', 'TEAM_MEMBER_DEMOTED', 'TEAM_MEMBER_REMOVED', 'TEAM_OWNERSHIP_TRANSFERRED', 'SCRIM_CREATED', 'SCRIM_UPDATED', 'SCRIM_DELETED', 'MAP_CREATED', 'MAP_UPDATED', 'MAP_DELETED', 'USER_AVATAR_UPDATED', 'USER_ACCOUNT_DELETED', 'USER_NAME_UPDATED', 'BUG_REPORT_SUBMITTED');

-- CreateTable
CREATE TABLE "public"."audit_log" (
    "id" SERIAL NOT NULL,
    "adminName" TEXT NOT NULL,
    "action" "public"."AuditLogAction" NOT NULL,
    "target" TEXT NOT NULL,
    "details" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "audit_log_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "audit_log_adminName_target_idx" ON "public"."audit_log"("adminName", "target");
