import type { Aggregation, DatasetId } from "@/lib/query-builder/types";
import { allHeroes } from "@/types/heroes";

/**
 * The query-builder registry. This is the single source of truth that drives
 * both the sentence-canvas UI (labels, options, the technical hover layer) and
 * the SQL compiler. It is intentionally client-safe: it holds only data and
 * pure lookups, never prisma or other server-only modules.
 *
 * Adding a new field or dataset is a data change here, not new code elsewhere.
 */

/** Where a column physically lives, so the planner knows which alias to use. */
export type ColumnSource = "base" | "match_start" | "scrim";

export type MetricDef = {
  id: string;
  label: string;
  description: string;
  /** display name of the table this metric reads from */
  table: string;
  /** underlying column, or null for pure row counts */
  column: string | null;
  source: ColumnSource;
  allowedAggs: Aggregation[];
  defaultAgg: Aggregation;
  unit?: string;
  precision: number;
  /** deaths, ult charge time, etc: a smaller number is the better result */
  lowerIsBetter?: boolean;
  /** CalculatedStat discriminator (the `stat` column value) */
  statType?: string;
  /** restrict a count to rows matching this SQL predicate (FILTER clause) */
  countFilter?: string;
  /** computed datasets only: multiply the aggregate (e.g. avg(won) × 100 = win %) */
  scale?: number;
  /** ratio/per10 metrics: denominator column to sum alongside the metric column */
  denominatorColumn?: string;
  /** ratio/per10 metrics: multiply SUM(column)/SUM(denominatorColumn) by this */
  denominatorScale?: number;
};

export type DimensionDef = {
  id: string;
  label: string;
  table: string;
  column: string;
  source: ColumnSource;
};

export type FilterValueType = "hero" | "player" | "text" | "number" | "enum";

export type FilterDef = {
  id: string;
  label: string;
  table: string;
  column: string;
  source: ColumnSource;
  valueType: FilterValueType;
  /** which operators this filter offers */
  operators: ("eq" | "neq" | "in" | "nin" | "gt" | "gte" | "lt" | "lte")[];
  /** fixed option list (enums); dynamic fields resolve options per team */
  enumOptions?: { value: string; label: string }[];
  /** for dynamic option resolution: the distinct column to pull from */
  optionsColumn?: string;
  optionsSource?: ColumnSource;
  unit?: string;
};

export type DatasetDef = {
  id: DatasetId;
  label: string;
  /** the noun used in the sentence ("player stats", "kills") */
  noun: string;
  description: string;
  table: string;
  /** human note about the row grain, shown in the technical reveal */
  grainNote: string;
  metrics: MetricDef[];
  dimensions: DimensionDef[];
  filters: FilterDef[];
  /**
   * "sql" (default) compiles to a team-scoped SQL query. "computed" runs a
   * server post-processing function (fight detection, win calc, ...) that SQL
   * can't express, then aggregates the result rows in memory.
   */
  kind?: "sql" | "computed";
  /** computed datasets: the raw tables the post-processing reads, for display */
  sourceTables?: string[];
};

const MAP_TYPES = [
  "Clash",
  "Control",
  "Escort",
  "Flashpoint",
  "Hybrid",
  "Push",
];
const ROLES = ["TANK", "DAMAGE", "SUPPORT"];
const HERO_OPTIONS = allHeroes.map((hero) => ({
  value: hero.name,
  label: hero.name,
}));
const ABILITY_OPTIONS = Array.from(
  new Set(allHeroes.flatMap((hero) => [hero.ability1.name, hero.ability2.name]))
)
  .sort((a, b) => a.localeCompare(b))
  .map((ability) => ({ value: ability, label: ability }));

const RATEABLE_AGGS: Aggregation[] = ["sum", "avg", "per10", "max", "min"];
const COUNTLESS_AGGS: Aggregation[] = ["sum", "avg", "max", "min"];

const mapTypeFilter: FilterDef = {
  id: "map_type",
  label: "map type",
  table: "MatchStart",
  column: "map_type",
  source: "match_start",
  valueType: "enum",
  operators: ["in", "nin"],
  enumOptions: MAP_TYPES.map((v) => ({ value: v, label: v })),
};

// --- numeric stat columns shared by PlayerStat metrics ----------------------
const PLAYER_STAT_COLUMNS: {
  id: string;
  label: string;
  column: string;
  unit?: string;
  precision?: number;
  lowerIsBetter?: boolean;
  rateable?: boolean;
}[] = [
  {
    id: "eliminations",
    label: "eliminations",
    column: "eliminations",
    rateable: true,
  },
  {
    id: "final_blows",
    label: "final blows",
    column: "final_blows",
    rateable: true,
  },
  {
    id: "deaths",
    label: "deaths",
    column: "deaths",
    lowerIsBetter: true,
    rateable: true,
  },
  {
    id: "hero_damage",
    label: "hero damage",
    column: "hero_damage_dealt",
    precision: 0,
    rateable: true,
  },
  {
    id: "all_damage",
    label: "all damage",
    column: "all_damage_dealt",
    precision: 0,
    rateable: true,
  },
  {
    id: "barrier_damage",
    label: "barrier damage",
    column: "barrier_damage_dealt",
    precision: 0,
    rateable: true,
  },
  {
    id: "healing",
    label: "healing dealt",
    column: "healing_dealt",
    precision: 0,
    rateable: true,
  },
  {
    id: "healing_received",
    label: "healing received",
    column: "healing_received",
    precision: 0,
    rateable: true,
  },
  {
    id: "self_healing",
    label: "self healing",
    column: "self_healing",
    precision: 0,
    rateable: true,
  },
  {
    id: "damage_taken",
    label: "damage taken",
    column: "damage_taken",
    precision: 0,
    lowerIsBetter: true,
    rateable: true,
  },
  {
    id: "damage_blocked",
    label: "damage blocked",
    column: "damage_blocked",
    precision: 0,
    rateable: true,
  },
  {
    id: "solo_kills",
    label: "solo kills",
    column: "solo_kills",
    rateable: true,
  },
  {
    id: "objective_kills",
    label: "objective kills",
    column: "objective_kills",
    rateable: true,
  },
  {
    id: "environmental_kills",
    label: "environmental kills",
    column: "environmental_kills",
    rateable: true,
  },
  {
    id: "ults_earned",
    label: "ultimates earned",
    column: "ultimates_earned",
    rateable: true,
  },
  {
    id: "ults_used",
    label: "ultimates used",
    column: "ultimates_used",
    rateable: true,
  },
  {
    id: "multikills",
    label: "multikills",
    column: "multikills",
    rateable: true,
  },
  {
    id: "offensive_assists",
    label: "offensive assists",
    column: "offensive_assists",
    rateable: true,
  },
  {
    id: "defensive_assists",
    label: "defensive assists",
    column: "defensive_assists",
    rateable: true,
  },
  {
    id: "critical_hits",
    label: "critical hits",
    column: "critical_hits",
    rateable: true,
  },
  {
    id: "shots_fired",
    label: "shots fired",
    column: "shots_fired",
    precision: 0,
    rateable: true,
  },
  {
    id: "shots_hit",
    label: "shots hit",
    column: "shots_hit",
    precision: 0,
    rateable: true,
  },
  {
    id: "time_played",
    label: "time played",
    column: "hero_time_played",
    unit: "s",
    precision: 0,
  },
];

const playerStatMetrics: MetricDef[] = PLAYER_STAT_COLUMNS.map((c) => ({
  id: c.id,
  label: c.label,
  description: `${c.label} recorded on PlayerStat`,
  table: "PlayerStat",
  column: c.column,
  source: "base" as const,
  allowedAggs: c.rateable ? RATEABLE_AGGS : COUNTLESS_AGGS,
  defaultAgg: "avg",
  unit: c.unit,
  precision: c.precision ?? 1,
  lowerIsBetter: c.lowerIsBetter,
}));
// A plain "maps counted" metric is always useful for context.
playerStatMetrics.unshift({
  id: "maps",
  label: "maps",
  description: "Number of maps the player appears on (final row per map)",
  table: "PlayerStat",
  column: null,
  source: "base",
  allowedAggs: ["count"],
  defaultAgg: "count",
  precision: 0,
});

// --- CalculatedStat metrics -------------------------------------------------
const CALC_METRICS: {
  id: string;
  label: string;
  statType: string;
  agg: Aggregation;
  unit?: string;
  precision: number;
  lowerIsBetter?: boolean;
}[] = [
  {
    id: "mvp_score",
    label: "MVP score",
    statType: "MVP_SCORE",
    agg: "avg",
    precision: 1,
  },
  {
    id: "map_mvp_count",
    label: "map MVPs",
    statType: "MAP_MVP_COUNT",
    agg: "sum",
    precision: 0,
  },
  {
    id: "fleta_deadlift",
    label: "Fleta deadlift %",
    statType: "FLETA_DEADLIFT_PERCENTAGE",
    agg: "avg",
    unit: "%",
    precision: 1,
  },
  {
    id: "first_pick_pct",
    label: "first pick %",
    statType: "FIRST_PICK_PERCENTAGE",
    agg: "avg",
    unit: "%",
    precision: 1,
  },
  {
    id: "first_pick_count",
    label: "first picks",
    statType: "FIRST_PICK_COUNT",
    agg: "sum",
    precision: 0,
  },
  {
    id: "first_death_pct",
    label: "first death %",
    statType: "FIRST_DEATH_PERCENTAGE",
    agg: "avg",
    unit: "%",
    precision: 1,
    lowerIsBetter: true,
  },
  {
    id: "first_death_count",
    label: "first deaths",
    statType: "FIRST_DEATH_COUNT",
    agg: "sum",
    precision: 0,
    lowerIsBetter: true,
  },
  {
    id: "ajax_count",
    label: "Ajaxes",
    statType: "AJAX_COUNT",
    agg: "sum",
    precision: 0,
  },
  {
    id: "ult_charge_time",
    label: "avg ult charge time",
    statType: "AVERAGE_ULT_CHARGE_TIME",
    agg: "avg",
    unit: "s",
    precision: 1,
    lowerIsBetter: true,
  },
  {
    id: "time_to_use_ult",
    label: "avg time to use ult",
    statType: "AVERAGE_TIME_TO_USE_ULT",
    agg: "avg",
    unit: "s",
    precision: 1,
    lowerIsBetter: true,
  },
  {
    id: "drought_time",
    label: "avg drought time",
    statType: "AVERAGE_DROUGHT_TIME",
    agg: "avg",
    unit: "s",
    precision: 1,
    lowerIsBetter: true,
  },
  {
    id: "kills_per_ult",
    label: "kills per ultimate",
    statType: "KILLS_PER_ULTIMATE",
    agg: "avg",
    precision: 2,
  },
  {
    id: "duel_winrate",
    label: "duel winrate %",
    statType: "DUEL_WINRATE_PERCENTAGE",
    agg: "avg",
    unit: "%",
    precision: 1,
  },
  {
    id: "fight_reversal",
    label: "fight reversal %",
    statType: "FIGHT_REVERSAL_PERCENTAGE",
    agg: "avg",
    unit: "%",
    precision: 1,
  },
];

const calculatedStatMetrics: MetricDef[] = CALC_METRICS.map((c) => ({
  id: c.id,
  label: c.label,
  description: `${c.label} from CalculatedStat (stat = ${c.statType})`,
  table: "CalculatedStat",
  column: "value",
  source: "base",
  allowedAggs: ["avg", "sum", "max", "min"],
  defaultAgg: c.agg,
  unit: c.unit,
  precision: c.precision,
  lowerIsBetter: c.lowerIsBetter,
  statType: c.statType,
}));

// --- Kill metrics -----------------------------------------------------------
const killMetrics: MetricDef[] = [
  {
    id: "kills",
    label: "kills",
    description: "Count of kill events",
    table: "Kill",
    column: null,
    source: "base",
    allowedAggs: ["count"],
    defaultAgg: "count",
    precision: 0,
  },
  {
    id: "critical_kills",
    label: "critical-hit kills",
    description: "Kill events where the killing blow was a critical hit",
    table: "Kill",
    column: null,
    source: "base",
    allowedAggs: ["count"],
    defaultAgg: "count",
    precision: 0,
    countFilter: "is_critical_hit = 'True'",
  },
  {
    id: "environmental_kills",
    label: "environmental kills",
    description: "Kill events flagged as environmental",
    table: "Kill",
    column: null,
    source: "base",
    allowedAggs: ["count"],
    defaultAgg: "count",
    precision: 0,
    countFilter: "is_environmental = 'True'",
  },
  {
    id: "kill_damage",
    label: "killing-blow damage",
    description: "Damage on the killing blow (event_damage)",
    table: "Kill",
    column: "event_damage",
    source: "base",
    allowedAggs: ["sum", "avg", "max", "min"],
    defaultAgg: "avg",
    precision: 0,
  },
];

function heroFilter(id: string, label: string, column: string): FilterDef {
  return {
    id,
    label,
    table: column === "player_hero" ? "PlayerStat" : "Kill",
    column,
    source: "base",
    valueType: "hero",
    operators: ["in", "nin"],
    optionsColumn: column,
    optionsSource: "base",
  };
}

export const DATASET_REGISTRY: Record<DatasetId, DatasetDef> = {
  player_stat: {
    id: "player_stat",
    label: "Player stats",
    noun: "player stats",
    description: "Per-player performance recorded each round of every map.",
    table: "PlayerStat",
    grainNote:
      "PlayerStat holds a cumulative row per player per round. The compiler keeps only the final row per map (DISTINCT ON MapDataId, player, hero) before aggregating, so totals are not double-counted.",
    metrics: playerStatMetrics,
    dimensions: [
      {
        id: "player",
        label: "player",
        table: "PlayerStat",
        column: "player_name",
        source: "base",
      },
      {
        id: "hero",
        label: "hero",
        table: "PlayerStat",
        column: "player_hero",
        source: "base",
      },
      {
        id: "in_game_team",
        label: "in-game team",
        table: "PlayerStat",
        column: "player_team",
        source: "base",
      },
      {
        id: "map",
        label: "map",
        table: "MatchStart",
        column: "map_name",
        source: "match_start",
      },
      {
        id: "map_type",
        label: "map type",
        table: "MatchStart",
        column: "map_type",
        source: "match_start",
      },
      {
        id: "scrim",
        label: "scrim",
        table: "Scrim",
        column: "name",
        source: "scrim",
      },
    ],
    filters: [
      heroFilter("hero", "hero", "player_hero"),
      {
        id: "player",
        label: "player",
        table: "PlayerStat",
        column: "player_name",
        source: "base",
        valueType: "player",
        operators: ["in", "nin"],
        optionsColumn: "player_name",
        optionsSource: "base",
      },
      {
        id: "in_game_team",
        label: "in-game team",
        table: "PlayerStat",
        column: "player_team",
        source: "base",
        valueType: "text",
        operators: ["in", "nin"],
        optionsColumn: "player_team",
        optionsSource: "base",
      },
      mapTypeFilter,
      {
        id: "min_time_played",
        label: "time played",
        table: "PlayerStat",
        column: "hero_time_played",
        source: "base",
        valueType: "number",
        operators: ["gte", "gt", "lte", "lt"],
        unit: "s",
      },
    ],
  },
  calculated_stat: {
    id: "calculated_stat",
    label: "Calculated stats",
    noun: "calculated stats",
    description:
      "Derived analytics like MVP score, duel winrate, and ult economy.",
    table: "CalculatedStat",
    grainNote:
      "CalculatedStat holds one row per map, player, hero, and stat type. Each metric reads its stat type with a FILTER clause, so several derived stats can be selected side by side.",
    metrics: calculatedStatMetrics,
    dimensions: [
      {
        id: "player",
        label: "player",
        table: "CalculatedStat",
        column: "playerName",
        source: "base",
      },
      {
        id: "hero",
        label: "hero",
        table: "CalculatedStat",
        column: "hero",
        source: "base",
      },
      {
        id: "role",
        label: "role",
        table: "CalculatedStat",
        column: "role",
        source: "base",
      },
      {
        id: "map_type",
        label: "map type",
        table: "MatchStart",
        column: "map_type",
        source: "match_start",
      },
      {
        id: "scrim",
        label: "scrim",
        table: "Scrim",
        column: "name",
        source: "scrim",
      },
    ],
    filters: [
      {
        id: "role",
        label: "role",
        table: "CalculatedStat",
        column: "role",
        source: "base",
        valueType: "enum",
        operators: ["in", "nin"],
        enumOptions: ROLES.map((r) => ({ value: r, label: r.toLowerCase() })),
      },
      heroFilter("hero", "hero", "hero"),
      {
        id: "player",
        label: "player",
        table: "CalculatedStat",
        column: "playerName",
        source: "base",
        valueType: "player",
        operators: ["in", "nin"],
        optionsColumn: "playerName",
        optionsSource: "base",
      },
      mapTypeFilter,
    ],
  },
  kill: {
    id: "kill",
    label: "Kills",
    noun: "kills",
    description: "Every kill event, with attacker, victim, hero, and ability.",
    table: "Kill",
    grainNote:
      "Kill holds one row per kill event, so counts are exact with no deduplication.",
    metrics: killMetrics,
    dimensions: [
      {
        id: "attacker",
        label: "attacker",
        table: "Kill",
        column: "attacker_name",
        source: "base",
      },
      {
        id: "attacker_hero",
        label: "attacker hero",
        table: "Kill",
        column: "attacker_hero",
        source: "base",
      },
      {
        id: "victim",
        label: "victim",
        table: "Kill",
        column: "victim_name",
        source: "base",
      },
      {
        id: "victim_hero",
        label: "victim hero",
        table: "Kill",
        column: "victim_hero",
        source: "base",
      },
      {
        id: "ability",
        label: "ability",
        table: "Kill",
        column: "event_ability",
        source: "base",
      },
      {
        id: "map_type",
        label: "map type",
        table: "MatchStart",
        column: "map_type",
        source: "match_start",
      },
      {
        id: "scrim",
        label: "scrim",
        table: "Scrim",
        column: "name",
        source: "scrim",
      },
    ],
    filters: [
      heroFilter("attacker_hero", "attacker hero", "attacker_hero"),
      heroFilter("victim_hero", "victim hero", "victim_hero"),
      {
        id: "attacker",
        label: "attacker",
        table: "Kill",
        column: "attacker_name",
        source: "base",
        valueType: "player",
        operators: ["in", "nin"],
        optionsColumn: "attacker_name",
        optionsSource: "base",
      },
      {
        id: "ability",
        label: "ability",
        table: "Kill",
        column: "event_ability",
        source: "base",
        valueType: "text",
        operators: ["in", "nin"],
        optionsColumn: "event_ability",
        optionsSource: "base",
      },
      {
        id: "critical",
        label: "critical hit",
        table: "Kill",
        column: "is_critical_hit",
        source: "base",
        valueType: "enum",
        operators: ["eq"],
        enumOptions: [
          { value: "True", label: "yes" },
          { value: "False", label: "no" },
        ],
      },
      mapTypeFilter,
    ],
  },
  hero_swap: {
    id: "hero_swap",
    label: "Hero swaps",
    noun: "hero swaps",
    description:
      "Every mid-map hero swap, with the heroes swapped from and to.",
    table: "HeroSwap",
    grainNote:
      "HeroSwap holds one row per swap event, so counts are exact with no deduplication.",
    metrics: [
      {
        id: "swaps",
        label: "swaps",
        description: "Count of hero swap events",
        table: "HeroSwap",
        column: null,
        source: "base",
        allowedAggs: ["count"],
        defaultAgg: "count",
        precision: 0,
      },
      {
        id: "time_before_swap",
        label: "time before swap",
        description: "Time played on the previous hero before swapping",
        table: "HeroSwap",
        column: "hero_time_played",
        source: "base",
        allowedAggs: ["avg", "sum", "max", "min"],
        defaultAgg: "avg",
        unit: "s",
        precision: 0,
      },
    ],
    dimensions: [
      {
        id: "player",
        label: "player",
        table: "HeroSwap",
        column: "player_name",
        source: "base",
      },
      {
        id: "to_hero",
        label: "swapped to",
        table: "HeroSwap",
        column: "player_hero",
        source: "base",
      },
      {
        id: "from_hero",
        label: "swapped from",
        table: "HeroSwap",
        column: "previous_hero",
        source: "base",
      },
      {
        id: "in_game_team",
        label: "in-game team",
        table: "HeroSwap",
        column: "player_team",
        source: "base",
      },
      {
        id: "map_type",
        label: "map type",
        table: "MatchStart",
        column: "map_type",
        source: "match_start",
      },
      {
        id: "scrim",
        label: "scrim",
        table: "Scrim",
        column: "name",
        source: "scrim",
      },
    ],
    filters: [
      {
        id: "player",
        label: "player",
        table: "HeroSwap",
        column: "player_name",
        source: "base",
        valueType: "player",
        operators: ["in", "nin"],
        optionsColumn: "player_name",
        optionsSource: "base",
      },
      {
        id: "to_hero",
        label: "swapped to",
        table: "HeroSwap",
        column: "player_hero",
        source: "base",
        valueType: "hero",
        operators: ["in", "nin"],
        optionsColumn: "player_hero",
        optionsSource: "base",
      },
      {
        id: "from_hero",
        label: "swapped from",
        table: "HeroSwap",
        column: "previous_hero",
        source: "base",
        valueType: "hero",
        operators: ["in", "nin"],
        optionsColumn: "previous_hero",
        optionsSource: "base",
      },
      mapTypeFilter,
    ],
  },
  ultimate: {
    id: "ultimate",
    label: "Ultimates",
    noun: "ultimates",
    description: "Every ultimate used, by player and hero.",
    table: "UltimateEnd",
    grainNote:
      "UltimateEnd holds one row per ultimate used, so counts are exact with no deduplication.",
    metrics: [
      {
        id: "ultimates",
        label: "ultimates",
        description: "Count of ultimates used",
        table: "UltimateEnd",
        column: null,
        source: "base",
        allowedAggs: ["count"],
        defaultAgg: "count",
        precision: 0,
      },
    ],
    dimensions: [
      {
        id: "player",
        label: "player",
        table: "UltimateEnd",
        column: "player_name",
        source: "base",
      },
      {
        id: "hero",
        label: "hero",
        table: "UltimateEnd",
        column: "player_hero",
        source: "base",
      },
      {
        id: "in_game_team",
        label: "in-game team",
        table: "UltimateEnd",
        column: "player_team",
        source: "base",
      },
      {
        id: "map_type",
        label: "map type",
        table: "MatchStart",
        column: "map_type",
        source: "match_start",
      },
      {
        id: "scrim",
        label: "scrim",
        table: "Scrim",
        column: "name",
        source: "scrim",
      },
    ],
    filters: [
      {
        id: "player",
        label: "player",
        table: "UltimateEnd",
        column: "player_name",
        source: "base",
        valueType: "player",
        operators: ["in", "nin"],
        optionsColumn: "player_name",
        optionsSource: "base",
      },
      {
        id: "hero",
        label: "hero",
        table: "UltimateEnd",
        column: "player_hero",
        source: "base",
        valueType: "hero",
        operators: ["in", "nin"],
        optionsColumn: "player_hero",
        optionsSource: "base",
      },
      mapTypeFilter,
    ],
  },
  map: {
    id: "map",
    label: "Maps",
    noun: "maps",
    description: "Maps played, by name, type, and opponent.",
    table: "MatchStart",
    grainNote:
      "MatchStart holds one row per map, so a count equals the number of maps played.",
    metrics: [
      {
        id: "maps",
        label: "maps",
        description: "Count of maps played",
        table: "MatchStart",
        column: null,
        source: "base",
        allowedAggs: ["count"],
        defaultAgg: "count",
        precision: 0,
      },
    ],
    dimensions: [
      {
        id: "map",
        label: "map",
        table: "MatchStart",
        column: "map_name",
        source: "base",
      },
      {
        id: "map_type",
        label: "map type",
        table: "MatchStart",
        column: "map_type",
        source: "base",
      },
      {
        id: "opponent",
        label: "opponent",
        table: "MatchStart",
        column: "team_2_name",
        source: "base",
      },
      {
        id: "scrim",
        label: "scrim",
        table: "Scrim",
        column: "name",
        source: "scrim",
      },
    ],
    filters: [
      {
        id: "map",
        label: "map",
        table: "MatchStart",
        column: "map_name",
        source: "base",
        valueType: "text",
        operators: ["in", "nin"],
        optionsColumn: "map_name",
        optionsSource: "base",
      },
      {
        id: "map_type",
        label: "map type",
        table: "MatchStart",
        column: "map_type",
        source: "base",
        valueType: "enum",
        operators: ["in", "nin"],
        enumOptions: MAP_TYPES.map((v) => ({ value: v, label: v })),
      },
    ],
  },
  teamfight: {
    id: "teamfight",
    label: "Teamfights",
    noun: "teamfights",
    description:
      "Every teamfight, with who won, how many ultimates your team spent, and tempo context.",
    table: "Teamfight",
    kind: "computed",
    sourceTables: ["Kill", "MercyRez", "UltimateStart", "MatchStart"],
    grainNote:
      "Kills, resurrections, and ultimates are clustered into fights (15-second gaps). Each fight's winner and your ultimates spent are computed in a post-processing step, since no SQL query can express it.",
    metrics: [
      {
        id: "fights",
        label: "fights",
        description: "Number of teamfights",
        table: "Teamfight",
        column: null,
        source: "base",
        allowedAggs: ["count"],
        defaultAgg: "count",
        precision: 0,
      },
      {
        id: "win_rate",
        label: "win rate",
        description: "Share of fights won (avg of won × 100)",
        table: "Teamfight",
        column: "won",
        source: "base",
        allowedAggs: ["avg"],
        defaultAgg: "avg",
        unit: "%",
        precision: 1,
        scale: 100,
      },
      {
        id: "wins",
        label: "wins",
        description: "Number of fights won",
        table: "Teamfight",
        column: "won",
        source: "base",
        allowedAggs: ["sum"],
        defaultAgg: "sum",
        precision: 0,
      },
      {
        id: "avg_ults",
        label: "avg ultimates used",
        description: "Average ultimates your team spent per fight",
        table: "Teamfight",
        column: "ults_used",
        source: "base",
        allowedAggs: ["avg", "max", "min"],
        defaultAgg: "avg",
        precision: 2,
      },
      {
        id: "avg_wasted_ults",
        label: "avg wasted ultimates",
        description:
          "Average ultimates spent after the fight was already heavily lost",
        table: "Teamfight",
        column: "wasted_ults",
        source: "base",
        allowedAggs: ["avg", "sum", "max"],
        defaultAgg: "avg",
        precision: 2,
        lowerIsBetter: true,
      },
      {
        id: "duration",
        label: "fight duration",
        description: "Length of each detected teamfight in seconds",
        table: "Teamfight",
        column: "duration",
        source: "base",
        allowedAggs: ["avg", "max", "min"],
        defaultAgg: "avg",
        unit: "s",
        precision: 1,
      },
    ],
    dimensions: [
      {
        id: "ults_used",
        label: "team ultimates used",
        table: "Teamfight",
        column: "ults_used",
        source: "base",
      },
      {
        id: "result",
        label: "result",
        table: "Teamfight",
        column: "result",
        source: "base",
      },
      {
        id: "first_pick",
        label: "first pick",
        table: "Teamfight",
        column: "first_pick",
        source: "base",
      },
      {
        id: "first_death",
        label: "first death",
        table: "Teamfight",
        column: "first_death",
        source: "base",
      },
      {
        id: "first_ult",
        label: "first ult",
        table: "Teamfight",
        column: "first_ult",
        source: "base",
      },
      {
        id: "dry_fight",
        label: "dry fight",
        table: "Teamfight",
        column: "dry_fight",
        source: "base",
      },
      {
        id: "reversal",
        label: "reversal",
        table: "Teamfight",
        column: "reversal",
        source: "base",
      },
      {
        id: "map",
        label: "map",
        table: "Teamfight",
        column: "map",
        source: "base",
      },
      {
        id: "map_type",
        label: "map type",
        table: "Teamfight",
        column: "map_type",
        source: "base",
      },
      {
        id: "scrim",
        label: "scrim",
        table: "Teamfight",
        column: "scrim",
        source: "base",
      },
    ],
    filters: [
      {
        id: "ults_used",
        label: "team ultimates used",
        table: "Teamfight",
        column: "ults_used",
        source: "base",
        valueType: "number",
        operators: ["eq", "gte", "lte", "gt", "lt"],
      },
      {
        id: "wasted_ults",
        label: "wasted ultimates",
        table: "Teamfight",
        column: "wasted_ults",
        source: "base",
        valueType: "number",
        operators: ["eq", "gte", "lte", "gt", "lt"],
      },
      {
        id: "map_type",
        label: "map type",
        table: "Teamfight",
        column: "map_type",
        source: "base",
        valueType: "enum",
        operators: ["in", "nin"],
        enumOptions: MAP_TYPES.map((v) => ({ value: v, label: v })),
      },
      {
        id: "map",
        label: "map",
        table: "Teamfight",
        column: "map",
        source: "base",
        valueType: "text",
        operators: ["in", "nin"],
      },
      {
        id: "result",
        label: "result",
        table: "Teamfight",
        column: "result",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "win", label: "win" },
          { value: "loss", label: "loss" },
        ],
      },
      {
        id: "first_pick",
        label: "first pick",
        table: "Teamfight",
        column: "first_pick",
        source: "base",
        valueType: "enum",
        operators: ["eq"],
        enumOptions: [
          { value: "yes", label: "yes" },
          { value: "no", label: "no" },
        ],
      },
      {
        id: "first_death",
        label: "first death",
        table: "Teamfight",
        column: "first_death",
        source: "base",
        valueType: "enum",
        operators: ["eq"],
        enumOptions: [
          { value: "yes", label: "yes" },
          { value: "no", label: "no" },
        ],
      },
      {
        id: "first_ult",
        label: "first ult",
        table: "Teamfight",
        column: "first_ult",
        source: "base",
        valueType: "enum",
        operators: ["eq"],
        enumOptions: [
          { value: "yes", label: "yes" },
          { value: "no", label: "no" },
        ],
      },
      {
        id: "dry_fight",
        label: "dry fight",
        table: "Teamfight",
        column: "dry_fight",
        source: "base",
        valueType: "enum",
        operators: ["eq"],
        enumOptions: [
          { value: "yes", label: "yes" },
          { value: "no", label: "no" },
        ],
      },
      {
        id: "reversal",
        label: "reversal",
        table: "Teamfight",
        column: "reversal",
        source: "base",
        valueType: "enum",
        operators: ["eq"],
        enumOptions: [
          { value: "yes", label: "yes" },
          { value: "no", label: "no" },
        ],
      },
    ],
  },
  map_result: {
    id: "map_result",
    label: "Map results",
    noun: "map results",
    description:
      "Win or loss on each map, computed with the same logic as the dashboards (objective progress, score, captures).",
    table: "MapResult",
    kind: "computed",
    sourceTables: [
      "MatchStart",
      "MatchEnd",
      "RoundEnd",
      "ObjectiveCaptured",
      "PayloadProgress",
      "PointProgress",
    ],
    grainNote:
      "One row per map. The winner is decided by calculateWinner() — objective progress, final score, and captures — which no SQL query can express, so it runs in a post-processing step.",
    metrics: [
      {
        id: "maps",
        label: "maps",
        description: "Number of maps played",
        table: "MapResult",
        column: null,
        source: "base",
        allowedAggs: ["count"],
        defaultAgg: "count",
        precision: 0,
      },
      {
        id: "win_rate",
        label: "win rate",
        description: "Share of maps won (avg of won × 100)",
        table: "MapResult",
        column: "won",
        source: "base",
        allowedAggs: ["avg"],
        defaultAgg: "avg",
        unit: "%",
        precision: 1,
        scale: 100,
      },
      {
        id: "wins",
        label: "wins",
        description: "Number of maps won",
        table: "MapResult",
        column: "won",
        source: "base",
        allowedAggs: ["sum"],
        defaultAgg: "sum",
        precision: 0,
      },
      {
        id: "losses",
        label: "losses",
        description: "Number of maps lost",
        table: "MapResult",
        column: "lost",
        source: "base",
        allowedAggs: ["sum"],
        defaultAgg: "sum",
        precision: 0,
        lowerIsBetter: true,
      },
      {
        id: "playtime",
        label: "map playtime",
        description: "Total match time on the map, from MatchEnd.match_time",
        table: "MapResult",
        column: "playtime",
        source: "base",
        allowedAggs: ["sum", "avg", "max"],
        defaultAgg: "sum",
        unit: "s",
        precision: 0,
      },
    ],
    dimensions: [
      {
        id: "result",
        label: "result",
        table: "MapResult",
        column: "result",
        source: "base",
      },
      {
        id: "map",
        label: "map",
        table: "MapResult",
        column: "map",
        source: "base",
      },
      {
        id: "map_type",
        label: "map type",
        table: "MapResult",
        column: "map_type",
        source: "base",
      },
      {
        id: "opponent",
        label: "opponent",
        table: "MapResult",
        column: "opponent",
        source: "base",
      },
      {
        id: "scrim",
        label: "scrim",
        table: "MapResult",
        column: "scrim",
        source: "base",
      },
    ],
    filters: [
      {
        id: "map",
        label: "map",
        table: "MapResult",
        column: "map",
        source: "base",
        valueType: "text",
        operators: ["in", "nin"],
      },
      {
        id: "opponent",
        label: "opponent",
        table: "MapResult",
        column: "opponent",
        source: "base",
        valueType: "text",
        operators: ["in", "nin"],
      },
      {
        id: "map_type",
        label: "map type",
        table: "MapResult",
        column: "map_type",
        source: "base",
        valueType: "enum",
        operators: ["in", "nin"],
        enumOptions: MAP_TYPES.map((v) => ({ value: v, label: v })),
      },
      {
        id: "result",
        label: "result",
        table: "MapResult",
        column: "result",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "win", label: "win" },
          { value: "loss", label: "loss" },
        ],
      },
    ],
  },
  ult_economy: {
    id: "ult_economy",
    label: "Ult economy",
    noun: "ult economy",
    description:
      "Win rate by the ultimate-bank advantage your team held entering each fight.",
    table: "UltEconomy",
    kind: "computed",
    sourceTables: ["Kill", "MercyRez", "UltimateStart", "UltimateCharged"],
    grainNote:
      "One row per fight. The ultimate bank each team carries into a fight is modelled from charge and use events, then correlated with the fight outcome — a post-processing step SQL can't do.",
    metrics: [
      {
        id: "win_rate",
        label: "win rate",
        description: "Share of fights won (avg of won × 100)",
        table: "UltEconomy",
        column: "won",
        source: "base",
        allowedAggs: ["avg"],
        defaultAgg: "avg",
        unit: "%",
        precision: 1,
        scale: 100,
      },
      {
        id: "fights",
        label: "fights",
        description: "Number of fights",
        table: "UltEconomy",
        column: null,
        source: "base",
        allowedAggs: ["count"],
        defaultAgg: "count",
        precision: 0,
      },
      {
        id: "avg_advantage",
        label: "avg ult advantage",
        description: "Average ult-bank advantage entering the fight",
        table: "UltEconomy",
        column: "advantage",
        source: "base",
        allowedAggs: ["avg", "max", "min"],
        defaultAgg: "avg",
        precision: 2,
      },
    ],
    dimensions: [
      {
        id: "advantage",
        label: "ult advantage",
        table: "UltEconomy",
        column: "advantage",
        source: "base",
      },
      {
        id: "advantage_bucket",
        label: "advantage bucket",
        table: "UltEconomy",
        column: "advantage_bucket",
        source: "base",
      },
      {
        id: "result",
        label: "result",
        table: "UltEconomy",
        column: "result",
        source: "base",
      },
      {
        id: "map_type",
        label: "map type",
        table: "UltEconomy",
        column: "map_type",
        source: "base",
      },
      {
        id: "scrim",
        label: "scrim",
        table: "UltEconomy",
        column: "scrim",
        source: "base",
      },
    ],
    filters: [
      {
        id: "advantage_bucket",
        label: "advantage bucket",
        table: "UltEconomy",
        column: "advantage_bucket",
        source: "base",
        valueType: "enum",
        operators: ["in", "nin"],
        enumOptions: [
          { value: "2+ behind", label: "2+ behind" },
          { value: "1 behind", label: "1 behind" },
          { value: "even", label: "even" },
          { value: "1 ahead", label: "1 ahead" },
          { value: "2+ ahead", label: "2+ ahead" },
        ],
      },
      {
        id: "map_type",
        label: "map type",
        table: "UltEconomy",
        column: "map_type",
        source: "base",
        valueType: "enum",
        operators: ["in", "nin"],
        enumOptions: MAP_TYPES.map((v) => ({ value: v, label: v })),
      },
      {
        id: "result",
        label: "result",
        table: "UltEconomy",
        column: "result",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "win", label: "win" },
          { value: "loss", label: "loss" },
        ],
      },
    ],
  },
  duel: {
    id: "duel",
    label: "Duels",
    noun: "duels",
    description:
      "1v1 kill/death win rate by hero matchup, from your team's perspective.",
    table: "Duel",
    kind: "computed",
    sourceTables: ["Kill"],
    grainNote:
      "One row per cross-team kill: a duel your team won (your player got the kill) or lost (your player died). Win rate is your kills over kills plus deaths for the matchup.",
    metrics: [
      {
        id: "win_rate",
        label: "duel win rate",
        description: "Share of duels won (avg of outcome × 100)",
        table: "Duel",
        column: "outcome",
        source: "base",
        allowedAggs: ["avg"],
        defaultAgg: "avg",
        unit: "%",
        precision: 1,
        scale: 100,
      },
      {
        id: "duels",
        label: "duels",
        description: "Number of duels (kills + deaths)",
        table: "Duel",
        column: null,
        source: "base",
        allowedAggs: ["count"],
        defaultAgg: "count",
        precision: 0,
      },
      {
        id: "wins",
        label: "duels won",
        description: "Number of duels won (kills)",
        table: "Duel",
        column: "outcome",
        source: "base",
        allowedAggs: ["sum"],
        defaultAgg: "sum",
        precision: 0,
      },
    ],
    dimensions: [
      {
        id: "our_hero",
        label: "our hero",
        table: "Duel",
        column: "our_hero",
        source: "base",
      },
      {
        id: "enemy_hero",
        label: "enemy hero",
        table: "Duel",
        column: "enemy_hero",
        source: "base",
      },
      {
        id: "map_type",
        label: "map type",
        table: "Duel",
        column: "map_type",
        source: "base",
      },
      {
        id: "scrim",
        label: "scrim",
        table: "Duel",
        column: "scrim",
        source: "base",
      },
    ],
    filters: [
      {
        id: "our_hero",
        label: "our hero",
        table: "Duel",
        column: "our_hero",
        source: "base",
        valueType: "hero",
        operators: ["in", "nin"],
        enumOptions: HERO_OPTIONS,
      },
      {
        id: "enemy_hero",
        label: "enemy hero",
        table: "Duel",
        column: "enemy_hero",
        source: "base",
        valueType: "hero",
        operators: ["in", "nin"],
        enumOptions: HERO_OPTIONS,
      },
      {
        id: "map_type",
        label: "map type",
        table: "Duel",
        column: "map_type",
        source: "base",
        valueType: "enum",
        operators: ["in", "nin"],
        enumOptions: MAP_TYPES.map((v) => ({ value: v, label: v })),
      },
    ],
  },
  ability_impact: {
    id: "ability_impact",
    label: "Ability impact",
    noun: "ability impact",
    description:
      "Fight win rate when specific hero abilities are or are not used by your team or the enemy.",
    table: "AbilityImpact",
    kind: "computed",
    sourceTables: ["Kill", "MercyRez", "Ability1Used", "Ability2Used"],
    grainNote:
      "One row per fight, hero, ability, and side. Ability usage is matched to fights with the same pre/post fight window as the team ability-impact dashboard, then aggregated in memory.",
    metrics: [
      {
        id: "win_rate",
        label: "win rate",
        description: "Share of fights won (avg of won × 100)",
        table: "AbilityImpact",
        column: "won",
        source: "base",
        allowedAggs: ["avg"],
        defaultAgg: "avg",
        unit: "%",
        precision: 1,
        scale: 100,
      },
      {
        id: "fights",
        label: "fights",
        description: "Number of fight/ability samples",
        table: "AbilityImpact",
        column: null,
        source: "base",
        allowedAggs: ["count"],
        defaultAgg: "count",
        precision: 0,
      },
      {
        id: "wins",
        label: "wins",
        description: "Number of fights won",
        table: "AbilityImpact",
        column: "won",
        source: "base",
        allowedAggs: ["sum"],
        defaultAgg: "sum",
        precision: 0,
      },
    ],
    dimensions: [
      {
        id: "hero",
        label: "hero",
        table: "AbilityImpact",
        column: "hero",
        source: "base",
      },
      {
        id: "ability",
        label: "ability",
        table: "AbilityImpact",
        column: "ability",
        source: "base",
      },
      {
        id: "side",
        label: "side",
        table: "AbilityImpact",
        column: "side",
        source: "base",
      },
      {
        id: "used",
        label: "used",
        table: "AbilityImpact",
        column: "used",
        source: "base",
      },
      {
        id: "scenario",
        label: "scenario",
        table: "AbilityImpact",
        column: "scenario",
        source: "base",
      },
      {
        id: "result",
        label: "result",
        table: "AbilityImpact",
        column: "result",
        source: "base",
      },
      {
        id: "map",
        label: "map",
        table: "AbilityImpact",
        column: "map",
        source: "base",
      },
      {
        id: "map_type",
        label: "map type",
        table: "AbilityImpact",
        column: "map_type",
        source: "base",
      },
      {
        id: "scrim",
        label: "scrim",
        table: "AbilityImpact",
        column: "scrim",
        source: "base",
      },
    ],
    filters: [
      {
        id: "hero",
        label: "hero",
        table: "AbilityImpact",
        column: "hero",
        source: "base",
        valueType: "hero",
        operators: ["in", "nin"],
        enumOptions: HERO_OPTIONS,
      },
      {
        id: "ability",
        label: "ability",
        table: "AbilityImpact",
        column: "ability",
        source: "base",
        valueType: "text",
        operators: ["in", "nin"],
        enumOptions: ABILITY_OPTIONS,
      },
      {
        id: "side",
        label: "side",
        table: "AbilityImpact",
        column: "side",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "us", label: "us" },
          { value: "enemy", label: "enemy" },
        ],
      },
      {
        id: "used",
        label: "used",
        table: "AbilityImpact",
        column: "used",
        source: "base",
        valueType: "enum",
        operators: ["eq"],
        enumOptions: [
          { value: "yes", label: "yes" },
          { value: "no", label: "no" },
        ],
      },
      {
        id: "scenario",
        label: "scenario",
        table: "AbilityImpact",
        column: "scenario",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "used by us", label: "used by us" },
          { value: "not used by us", label: "not used by us" },
          { value: "used by enemy", label: "used by enemy" },
          { value: "not used by enemy", label: "not used by enemy" },
        ],
      },
      {
        id: "map",
        label: "map",
        table: "AbilityImpact",
        column: "map",
        source: "base",
        valueType: "text",
        operators: ["in", "nin"],
      },
      {
        id: "map_type",
        label: "map type",
        table: "AbilityImpact",
        column: "map_type",
        source: "base",
        valueType: "enum",
        operators: ["in", "nin"],
        enumOptions: MAP_TYPES.map((v) => ({ value: v, label: v })),
      },
    ],
  },
  swap_impact: {
    id: "swap_impact",
    label: "Swap impact",
    noun: "swap impact",
    description:
      "Map win rate by whether your team swapped, how many swaps happened, and when the first swap occurred.",
    table: "SwapImpact",
    kind: "computed",
    sourceTables: [
      "HeroSwap",
      "MatchStart",
      "RoundEnd",
      "ObjectiveCaptured",
      "PayloadProgress",
      "PointProgress",
    ],
    grainNote:
      "One row per map. The map winner is computed with calculateWinner(), then your team's HeroSwap events are bucketed by count and first-swap timing in post-processing.",
    metrics: [
      {
        id: "win_rate",
        label: "win rate",
        description: "Share of maps won (avg of won × 100)",
        table: "SwapImpact",
        column: "won",
        source: "base",
        allowedAggs: ["avg"],
        defaultAgg: "avg",
        unit: "%",
        precision: 1,
        scale: 100,
      },
      {
        id: "maps",
        label: "maps",
        description: "Number of maps",
        table: "SwapImpact",
        column: null,
        source: "base",
        allowedAggs: ["count"],
        defaultAgg: "count",
        precision: 0,
      },
      {
        id: "wins",
        label: "wins",
        description: "Number of maps won",
        table: "SwapImpact",
        column: "won",
        source: "base",
        allowedAggs: ["sum"],
        defaultAgg: "sum",
        precision: 0,
      },
      {
        id: "avg_swaps",
        label: "avg swaps",
        description: "Average swaps per map",
        table: "SwapImpact",
        column: "swap_count",
        source: "base",
        allowedAggs: ["avg", "max", "min"],
        defaultAgg: "avg",
        precision: 2,
      },
    ],
    dimensions: [
      {
        id: "had_swap",
        label: "had swap",
        table: "SwapImpact",
        column: "had_swap",
        source: "base",
      },
      {
        id: "swap_count",
        label: "swap count",
        table: "SwapImpact",
        column: "swap_count",
        source: "base",
      },
      {
        id: "swap_count_bucket",
        label: "swap count bucket",
        table: "SwapImpact",
        column: "swap_count_bucket",
        source: "base",
      },
      {
        id: "first_swap_timing",
        label: "first swap timing",
        table: "SwapImpact",
        column: "first_swap_timing",
        source: "base",
      },
      {
        id: "result",
        label: "result",
        table: "SwapImpact",
        column: "result",
        source: "base",
      },
      {
        id: "map",
        label: "map",
        table: "SwapImpact",
        column: "map",
        source: "base",
      },
      {
        id: "map_type",
        label: "map type",
        table: "SwapImpact",
        column: "map_type",
        source: "base",
      },
      {
        id: "scrim",
        label: "scrim",
        table: "SwapImpact",
        column: "scrim",
        source: "base",
      },
    ],
    filters: [
      {
        id: "had_swap",
        label: "had swap",
        table: "SwapImpact",
        column: "had_swap",
        source: "base",
        valueType: "enum",
        operators: ["eq"],
        enumOptions: [
          { value: "yes", label: "yes" },
          { value: "no", label: "no" },
        ],
      },
      {
        id: "swap_count",
        label: "swap count",
        table: "SwapImpact",
        column: "swap_count",
        source: "base",
        valueType: "number",
        operators: ["eq", "gte", "lte", "gt", "lt"],
      },
      {
        id: "swap_count_bucket",
        label: "swap count bucket",
        table: "SwapImpact",
        column: "swap_count_bucket",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "0 swaps", label: "0 swaps" },
          { value: "1 swap", label: "1 swap" },
          { value: "2 swaps", label: "2 swaps" },
          { value: "3+ swaps", label: "3+ swaps" },
        ],
      },
      {
        id: "first_swap_timing",
        label: "first swap timing",
        table: "SwapImpact",
        column: "first_swap_timing",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "none", label: "none" },
          { value: "early", label: "early" },
          { value: "mid", label: "mid" },
          { value: "late", label: "late" },
        ],
      },
      {
        id: "map",
        label: "map",
        table: "SwapImpact",
        column: "map",
        source: "base",
        valueType: "text",
        operators: ["in", "nin"],
      },
      {
        id: "map_type",
        label: "map type",
        table: "SwapImpact",
        column: "map_type",
        source: "base",
        valueType: "enum",
        operators: ["in", "nin"],
        enumOptions: MAP_TYPES.map((v) => ({ value: v, label: v })),
      },
    ],
  },
  hero_pool: {
    id: "hero_pool",
    label: "Hero pool",
    noun: "hero pool",
    description:
      "Hero playtime, role slices, and computed map win rate for heroes your team played.",
    table: "HeroPool",
    kind: "computed",
    sourceTables: [
      "PlayerStat",
      "MatchStart",
      "RoundEnd",
      "ObjectiveCaptured",
      "PayloadProgress",
      "PointProgress",
    ],
    grainNote:
      "One row per player/hero/map appearance for your team. The map winner is computed with calculateWinner(), and hero role is derived from the same hero-role mapping as the team hero-pool dashboard.",
    metrics: [
      {
        id: "win_rate",
        label: "win rate",
        description:
          "Share of hero-map appearances on maps won (avg of won × 100)",
        table: "HeroPool",
        column: "won",
        source: "base",
        allowedAggs: ["avg"],
        defaultAgg: "avg",
        unit: "%",
        precision: 1,
        scale: 100,
      },
      {
        id: "appearances",
        label: "appearances",
        description: "Number of player/hero/map appearances",
        table: "HeroPool",
        column: null,
        source: "base",
        allowedAggs: ["count"],
        defaultAgg: "count",
        precision: 0,
      },
      {
        id: "time_played",
        label: "time played",
        description: "Total hero time played",
        table: "HeroPool",
        column: "time_played",
        source: "base",
        allowedAggs: ["sum", "avg", "max", "min"],
        defaultAgg: "sum",
        unit: "s",
        precision: 0,
      },
      {
        id: "final_blows",
        label: "final blows",
        description: "Final blows recorded on this hero slice",
        table: "HeroPool",
        column: "final_blows",
        source: "base",
        allowedAggs: ["sum", "avg", "per10", "max"],
        defaultAgg: "sum",
        precision: 0,
        denominatorColumn: "time_played",
        denominatorScale: 600,
      },
      {
        id: "eliminations",
        label: "eliminations",
        description: "Eliminations recorded on this hero slice",
        table: "HeroPool",
        column: "eliminations",
        source: "base",
        allowedAggs: ["sum", "avg", "per10", "max"],
        defaultAgg: "sum",
        precision: 1,
        denominatorColumn: "time_played",
        denominatorScale: 600,
      },
      {
        id: "deaths",
        label: "deaths",
        description: "Deaths recorded on this hero slice",
        table: "HeroPool",
        column: "deaths",
        source: "base",
        allowedAggs: ["sum", "avg", "per10", "max"],
        defaultAgg: "sum",
        precision: 1,
        lowerIsBetter: true,
        denominatorColumn: "time_played",
        denominatorScale: 600,
      },
      {
        id: "assists",
        label: "assists",
        description: "Offensive assists recorded on this hero slice",
        table: "HeroPool",
        column: "assists",
        source: "base",
        allowedAggs: ["sum", "avg", "per10", "max"],
        defaultAgg: "sum",
        precision: 1,
        denominatorColumn: "time_played",
        denominatorScale: 600,
      },
      {
        id: "hero_damage",
        label: "hero damage",
        description: "Hero damage recorded on this hero slice",
        table: "HeroPool",
        column: "hero_damage",
        source: "base",
        allowedAggs: ["sum", "avg", "per10", "max"],
        defaultAgg: "sum",
        precision: 0,
        denominatorColumn: "time_played",
        denominatorScale: 600,
      },
      {
        id: "damage_taken",
        label: "damage taken",
        description: "Damage taken recorded on this hero slice",
        table: "HeroPool",
        column: "damage_taken",
        source: "base",
        allowedAggs: ["sum", "avg", "per10", "max"],
        defaultAgg: "sum",
        precision: 0,
        lowerIsBetter: true,
        denominatorColumn: "time_played",
        denominatorScale: 600,
      },
      {
        id: "healing",
        label: "healing dealt",
        description: "Healing recorded on this hero slice",
        table: "HeroPool",
        column: "healing",
        source: "base",
        allowedAggs: ["sum", "avg", "per10", "max"],
        defaultAgg: "sum",
        precision: 0,
        denominatorColumn: "time_played",
        denominatorScale: 600,
      },
      {
        id: "ultimates_earned",
        label: "ultimates earned",
        description: "Ultimates earned on this hero slice",
        table: "HeroPool",
        column: "ultimates_earned",
        source: "base",
        allowedAggs: ["sum", "avg", "per10", "max"],
        defaultAgg: "sum",
        precision: 1,
        denominatorColumn: "time_played",
        denominatorScale: 600,
      },
      {
        id: "ultimates_used",
        label: "ultimates used",
        description: "Ultimates used on this hero slice",
        table: "HeroPool",
        column: "ultimates_used",
        source: "base",
        allowedAggs: ["sum", "avg", "per10", "max"],
        defaultAgg: "sum",
        precision: 1,
        denominatorColumn: "time_played",
        denominatorScale: 600,
      },
      {
        id: "kd",
        label: "final-blow K/D",
        description: "Final blows divided by deaths for this hero slice",
        table: "HeroPool",
        column: "final_blows",
        source: "base",
        allowedAggs: ["ratio"],
        defaultAgg: "ratio",
        precision: 2,
        denominatorColumn: "deaths",
      },
      {
        id: "ult_efficiency",
        label: "ultimate efficiency",
        description: "Eliminations divided by ultimates used",
        table: "HeroPool",
        column: "eliminations",
        source: "base",
        allowedAggs: ["ratio"],
        defaultAgg: "ratio",
        precision: 2,
        denominatorColumn: "ultimates_used",
      },
    ],
    dimensions: [
      {
        id: "hero",
        label: "hero",
        table: "HeroPool",
        column: "hero",
        source: "base",
      },
      {
        id: "role",
        label: "role",
        table: "HeroPool",
        column: "role",
        source: "base",
      },
      {
        id: "player",
        label: "player",
        table: "HeroPool",
        column: "player",
        source: "base",
      },
      {
        id: "result",
        label: "result",
        table: "HeroPool",
        column: "result",
        source: "base",
      },
      {
        id: "map",
        label: "map",
        table: "HeroPool",
        column: "map",
        source: "base",
      },
      {
        id: "map_type",
        label: "map type",
        table: "HeroPool",
        column: "map_type",
        source: "base",
      },
      {
        id: "scrim",
        label: "scrim",
        table: "HeroPool",
        column: "scrim",
        source: "base",
      },
    ],
    filters: [
      {
        id: "hero",
        label: "hero",
        table: "HeroPool",
        column: "hero",
        source: "base",
        valueType: "hero",
        operators: ["in", "nin"],
        enumOptions: HERO_OPTIONS,
      },
      {
        id: "role",
        label: "role",
        table: "HeroPool",
        column: "role",
        source: "base",
        valueType: "enum",
        operators: ["in", "nin"],
        enumOptions: ["Tank", "Damage", "Support"].map((role) => ({
          value: role,
          label: role,
        })),
      },
      {
        id: "player",
        label: "player",
        table: "HeroPool",
        column: "player",
        source: "base",
        valueType: "player",
        operators: ["in", "nin"],
      },
      {
        id: "map",
        label: "map",
        table: "HeroPool",
        column: "map",
        source: "base",
        valueType: "text",
        operators: ["in", "nin"],
      },
      {
        id: "map_type",
        label: "map type",
        table: "HeroPool",
        column: "map_type",
        source: "base",
        valueType: "enum",
        operators: ["in", "nin"],
        enumOptions: MAP_TYPES.map((v) => ({ value: v, label: v })),
      },
    ],
  },
  enemy_hero: {
    id: "enemy_hero",
    label: "Enemy heroes",
    noun: "enemy hero matchups",
    description:
      "Map win rate against enemy heroes your team faced, grouped by hero, role, map, or scrim.",
    table: "EnemyHeroMatchup",
    kind: "computed",
    sourceTables: [
      "PlayerStat",
      "MatchStart",
      "RoundEnd",
      "ObjectiveCaptured",
      "PayloadProgress",
      "PointProgress",
    ],
    grainNote:
      "One row per map and distinct enemy hero appearance. The map winner is computed with calculateWinner(), and enemy hero role is derived from the shared hero-role mapping.",
    metrics: [
      {
        id: "win_rate",
        label: "win rate",
        description:
          "Share of maps won against the enemy hero (avg of won × 100)",
        table: "EnemyHeroMatchup",
        column: "won",
        source: "base",
        allowedAggs: ["avg"],
        defaultAgg: "avg",
        unit: "%",
        precision: 1,
        scale: 100,
      },
      {
        id: "maps",
        label: "maps",
        description: "Number of map/enemy-hero samples",
        table: "EnemyHeroMatchup",
        column: null,
        source: "base",
        allowedAggs: ["count"],
        defaultAgg: "count",
        precision: 0,
      },
      {
        id: "wins",
        label: "wins",
        description: "Number of maps won against the enemy hero",
        table: "EnemyHeroMatchup",
        column: "won",
        source: "base",
        allowedAggs: ["sum"],
        defaultAgg: "sum",
        precision: 0,
      },
    ],
    dimensions: [
      {
        id: "enemy_hero",
        label: "enemy hero",
        table: "EnemyHeroMatchup",
        column: "enemy_hero",
        source: "base",
      },
      {
        id: "enemy_role",
        label: "enemy role",
        table: "EnemyHeroMatchup",
        column: "enemy_role",
        source: "base",
      },
      {
        id: "result",
        label: "result",
        table: "EnemyHeroMatchup",
        column: "result",
        source: "base",
      },
      {
        id: "map",
        label: "map",
        table: "EnemyHeroMatchup",
        column: "map",
        source: "base",
      },
      {
        id: "map_type",
        label: "map type",
        table: "EnemyHeroMatchup",
        column: "map_type",
        source: "base",
      },
      {
        id: "scrim",
        label: "scrim",
        table: "EnemyHeroMatchup",
        column: "scrim",
        source: "base",
      },
    ],
    filters: [
      {
        id: "enemy_hero",
        label: "enemy hero",
        table: "EnemyHeroMatchup",
        column: "enemy_hero",
        source: "base",
        valueType: "hero",
        operators: ["in", "nin"],
        enumOptions: HERO_OPTIONS,
      },
      {
        id: "enemy_role",
        label: "enemy role",
        table: "EnemyHeroMatchup",
        column: "enemy_role",
        source: "base",
        valueType: "enum",
        operators: ["in", "nin"],
        enumOptions: ["Tank", "Damage", "Support"].map((role) => ({
          value: role,
          label: role,
        })),
      },
      {
        id: "map",
        label: "map",
        table: "EnemyHeroMatchup",
        column: "map",
        source: "base",
        valueType: "text",
        operators: ["in", "nin"],
      },
      {
        id: "map_type",
        label: "map type",
        table: "EnemyHeroMatchup",
        column: "map_type",
        source: "base",
        valueType: "enum",
        operators: ["in", "nin"],
        enumOptions: MAP_TYPES.map((v) => ({ value: v, label: v })),
      },
    ],
  },
  ban_impact: {
    id: "ban_impact",
    label: "Ban impact",
    noun: "hero ban impact",
    description:
      "How hero bans relate to map win rate, including bans against your team and bans your team made.",
    table: "BanImpact",
    kind: "computed",
    sourceTables: [
      "HeroBan",
      "PlayerStat",
      "MatchStart",
      "RoundEnd",
      "ObjectiveCaptured",
      "PayloadProgress",
      "PointProgress",
    ],
    grainNote:
      "One summary row per hero and ban direction. The map winner is computed with calculateWinner(), then ban rate and with/without win-rate deltas are derived from the same ban-impact service used by the team dashboard.",
    metrics: [
      {
        id: "ban_rate",
        label: "ban rate",
        description: "Share of analyzed maps where this hero was banned",
        table: "BanImpact",
        column: "ban_rate",
        source: "base",
        allowedAggs: ["avg", "max", "min"],
        defaultAgg: "avg",
        unit: "%",
        precision: 1,
        scale: 100,
      },
      {
        id: "maps_banned",
        label: "maps banned",
        description: "Number of maps where this hero was banned",
        table: "BanImpact",
        column: "maps_banned",
        source: "base",
        allowedAggs: ["sum", "avg", "max"],
        defaultAgg: "sum",
        precision: 0,
      },
      {
        id: "maps_played",
        label: "maps analyzed",
        description: "Number of maps analyzed for this ban-impact row",
        table: "BanImpact",
        column: "maps_played",
        source: "base",
        allowedAggs: ["max", "avg"],
        defaultAgg: "max",
        precision: 0,
      },
      {
        id: "win_rate_with",
        label: "win rate with ban",
        description:
          "Received bans: win rate when the hero was available. Outgoing bans: win rate when we banned the hero.",
        table: "BanImpact",
        column: "win_rate_with",
        source: "base",
        allowedAggs: ["avg", "max", "min"],
        defaultAgg: "avg",
        unit: "%",
        precision: 1,
        scale: 100,
      },
      {
        id: "win_rate_without",
        label: "win rate without ban",
        description:
          "Received bans: win rate when the hero was banned from us. Outgoing bans: win rate when we did not ban the hero.",
        table: "BanImpact",
        column: "win_rate_without",
        source: "base",
        allowedAggs: ["avg", "max", "min"],
        defaultAgg: "avg",
        unit: "%",
        precision: 1,
        scale: 100,
      },
      {
        id: "win_rate_delta",
        label: "win-rate delta",
        description:
          "Received bans: available win rate minus banned win rate. Outgoing bans: banned win rate minus not-banned win rate.",
        table: "BanImpact",
        column: "win_rate_delta",
        source: "base",
        allowedAggs: ["avg", "max", "min"],
        defaultAgg: "avg",
        unit: "pp",
        precision: 1,
        scale: 100,
      },
    ],
    dimensions: [
      {
        id: "hero",
        label: "hero",
        table: "BanImpact",
        column: "hero",
        source: "base",
      },
      {
        id: "side",
        label: "ban side",
        table: "BanImpact",
        column: "side",
        source: "base",
      },
      {
        id: "tag",
        label: "tag",
        table: "BanImpact",
        column: "tag",
        source: "base",
      },
    ],
    filters: [
      {
        id: "hero",
        label: "hero",
        table: "BanImpact",
        column: "hero",
        source: "base",
        valueType: "hero",
        operators: ["in", "nin"],
        enumOptions: HERO_OPTIONS,
      },
      {
        id: "side",
        label: "ban side",
        table: "BanImpact",
        column: "side",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "banned by enemy", label: "banned by enemy" },
          { value: "banned by us", label: "banned by us" },
        ],
      },
      {
        id: "tag",
        label: "tag",
        table: "BanImpact",
        column: "tag",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "weak point", label: "weak point" },
          { value: "strong ban", label: "strong ban" },
          { value: "normal", label: "normal" },
        ],
      },
    ],
  },
  ult_combo: {
    id: "ult_combo",
    label: "Ult combos",
    noun: "ult combos",
    description:
      "Fight win rate for two-ultimate combos and counter-ult responses.",
    table: "UltCombo",
    kind: "computed",
    sourceTables: ["PlayerStat", "Kill", "MercyRez", "UltimateStart"],
    grainNote:
      "One summary row per friendly two-ultimate combo and one per counter-ult response. Combos and responses reuse the same fight-scoped post-processing as the team ult-combos dashboard, then query metrics aggregate those summaries in memory.",
    metrics: [
      {
        id: "win_rate",
        label: "win rate",
        description: "Weighted fight win rate (wins divided by uses × 100)",
        table: "UltCombo",
        column: "wins",
        source: "base",
        allowedAggs: ["ratio"],
        defaultAgg: "ratio",
        unit: "%",
        precision: 1,
        denominatorColumn: "uses",
        scale: 100,
      },
      {
        id: "uses",
        label: "uses",
        description: "Number of fights containing the combo or response",
        table: "UltCombo",
        column: "uses",
        source: "base",
        allowedAggs: ["sum", "avg", "max"],
        defaultAgg: "sum",
        precision: 0,
      },
      {
        id: "wins",
        label: "wins",
        description: "Number of fights won with the combo or response",
        table: "UltCombo",
        column: "wins",
        source: "base",
        allowedAggs: ["sum", "avg", "max"],
        defaultAgg: "sum",
        precision: 0,
      },
      {
        id: "losses",
        label: "losses",
        description: "Number of fights lost with the combo or response",
        table: "UltCombo",
        column: "losses",
        source: "base",
        allowedAggs: ["sum", "avg", "max"],
        defaultAgg: "sum",
        precision: 0,
        lowerIsBetter: true,
      },
    ],
    dimensions: [
      {
        id: "combo",
        label: "combo",
        table: "UltCombo",
        column: "combo",
        source: "base",
      },
      {
        id: "type",
        label: "type",
        table: "UltCombo",
        column: "type",
        source: "base",
      },
      {
        id: "hero_a",
        label: "first hero",
        table: "UltCombo",
        column: "hero_a",
        source: "base",
      },
      {
        id: "hero_b",
        label: "second hero",
        table: "UltCombo",
        column: "hero_b",
        source: "base",
      },
      {
        id: "enemy_hero",
        label: "enemy ult hero",
        table: "UltCombo",
        column: "enemy_hero",
        source: "base",
      },
      {
        id: "response_hero",
        label: "response hero",
        table: "UltCombo",
        column: "response_hero",
        source: "base",
      },
    ],
    filters: [
      {
        id: "type",
        label: "type",
        table: "UltCombo",
        column: "type",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "combo", label: "combo" },
          { value: "response", label: "response" },
        ],
      },
      {
        id: "hero",
        label: "hero",
        table: "UltCombo",
        column: "hero",
        source: "base",
        valueType: "hero",
        operators: ["in", "nin"],
        enumOptions: HERO_OPTIONS,
      },
      {
        id: "hero_a",
        label: "first hero",
        table: "UltCombo",
        column: "hero_a",
        source: "base",
        valueType: "hero",
        operators: ["in", "nin"],
        enumOptions: HERO_OPTIONS,
      },
      {
        id: "hero_b",
        label: "second hero",
        table: "UltCombo",
        column: "hero_b",
        source: "base",
        valueType: "hero",
        operators: ["in", "nin"],
        enumOptions: HERO_OPTIONS,
      },
      {
        id: "enemy_hero",
        label: "enemy ult hero",
        table: "UltCombo",
        column: "enemy_hero",
        source: "base",
        valueType: "hero",
        operators: ["in", "nin"],
        enumOptions: HERO_OPTIONS,
      },
      {
        id: "response_hero",
        label: "response hero",
        table: "UltCombo",
        column: "response_hero",
        source: "base",
        valueType: "hero",
        operators: ["in", "nin"],
        enumOptions: HERO_OPTIONS,
      },
    ],
  },
  role_trio: {
    id: "role_trio",
    label: "Role trios",
    noun: "role trios",
    description:
      "Map win rate for five-player lineups with one tank, two damage, and two support players.",
    table: "RoleTrio",
    kind: "computed",
    sourceTables: [
      "PlayerStat",
      "MatchStart",
      "RoundEnd",
      "ObjectiveCaptured",
      "PayloadProgress",
      "PointProgress",
    ],
    grainNote:
      "One summary row per qualifying five-player role lineup. The map winner is computed with calculateWinner(), and lineups below the dashboard's three-map sample threshold are omitted.",
    metrics: [
      {
        id: "win_rate",
        label: "win rate",
        description: "Weighted map win rate (wins divided by games × 100)",
        table: "RoleTrio",
        column: "wins",
        source: "base",
        allowedAggs: ["ratio"],
        defaultAgg: "ratio",
        unit: "%",
        precision: 1,
        denominatorColumn: "games",
        scale: 100,
      },
      {
        id: "games",
        label: "games",
        description: "Number of maps played by the lineup",
        table: "RoleTrio",
        column: "games",
        source: "base",
        allowedAggs: ["sum", "avg", "max"],
        defaultAgg: "sum",
        precision: 0,
      },
      {
        id: "wins",
        label: "wins",
        description: "Number of maps won by the lineup",
        table: "RoleTrio",
        column: "wins",
        source: "base",
        allowedAggs: ["sum", "avg", "max"],
        defaultAgg: "sum",
        precision: 0,
      },
      {
        id: "losses",
        label: "losses",
        description: "Number of maps lost by the lineup",
        table: "RoleTrio",
        column: "losses",
        source: "base",
        allowedAggs: ["sum", "avg", "max"],
        defaultAgg: "sum",
        precision: 0,
        lowerIsBetter: true,
      },
    ],
    dimensions: [
      {
        id: "trio",
        label: "lineup",
        table: "RoleTrio",
        column: "trio",
        source: "base",
      },
      {
        id: "tank",
        label: "tank",
        table: "RoleTrio",
        column: "tank",
        source: "base",
      },
      {
        id: "dps1",
        label: "damage 1",
        table: "RoleTrio",
        column: "dps1",
        source: "base",
      },
      {
        id: "dps2",
        label: "damage 2",
        table: "RoleTrio",
        column: "dps2",
        source: "base",
      },
      {
        id: "support1",
        label: "support 1",
        table: "RoleTrio",
        column: "support1",
        source: "base",
      },
      {
        id: "support2",
        label: "support 2",
        table: "RoleTrio",
        column: "support2",
        source: "base",
      },
    ],
    filters: [
      {
        id: "player",
        label: "player",
        table: "RoleTrio",
        column: "player",
        source: "base",
        valueType: "player",
        operators: ["in", "nin"],
      },
      {
        id: "tank",
        label: "tank",
        table: "RoleTrio",
        column: "tank",
        source: "base",
        valueType: "player",
        operators: ["in", "nin"],
      },
      {
        id: "dps1",
        label: "damage 1",
        table: "RoleTrio",
        column: "dps1",
        source: "base",
        valueType: "player",
        operators: ["in", "nin"],
      },
      {
        id: "dps2",
        label: "damage 2",
        table: "RoleTrio",
        column: "dps2",
        source: "base",
        valueType: "player",
        operators: ["in", "nin"],
      },
      {
        id: "support1",
        label: "support 1",
        table: "RoleTrio",
        column: "support1",
        source: "base",
        valueType: "player",
        operators: ["in", "nin"],
      },
      {
        id: "support2",
        label: "support 2",
        table: "RoleTrio",
        column: "support2",
        source: "base",
        valueType: "player",
        operators: ["in", "nin"],
      },
    ],
  },
  roster_variant: {
    id: "roster_variant",
    label: "Roster variants",
    noun: "map roster variants",
    description:
      "Map win rate for exact five-player rosters, including the best roster on each map.",
    table: "RosterVariant",
    kind: "computed",
    sourceTables: [
      "PlayerStat",
      "MatchStart",
      "RoundEnd",
      "ObjectiveCaptured",
      "PayloadProgress",
      "PointProgress",
    ],
    grainNote:
      "One summary row per map and exact five-player roster. The map winner is computed with calculateWinner(), matching the roster-variant breakdown in team winrates.",
    metrics: [
      {
        id: "win_rate",
        label: "win rate",
        description: "Weighted map win rate (wins divided by games × 100)",
        table: "RosterVariant",
        column: "wins",
        source: "base",
        allowedAggs: ["ratio"],
        defaultAgg: "ratio",
        unit: "%",
        precision: 1,
        denominatorColumn: "games",
        scale: 100,
      },
      {
        id: "games",
        label: "games",
        description: "Number of maps played by the roster",
        table: "RosterVariant",
        column: "games",
        source: "base",
        allowedAggs: ["sum", "avg", "max"],
        defaultAgg: "sum",
        precision: 0,
      },
      {
        id: "wins",
        label: "wins",
        description: "Number of maps won by the roster",
        table: "RosterVariant",
        column: "wins",
        source: "base",
        allowedAggs: ["sum", "avg", "max"],
        defaultAgg: "sum",
        precision: 0,
      },
      {
        id: "losses",
        label: "losses",
        description: "Number of maps lost by the roster",
        table: "RosterVariant",
        column: "losses",
        source: "base",
        allowedAggs: ["sum", "avg", "max"],
        defaultAgg: "sum",
        precision: 0,
        lowerIsBetter: true,
      },
    ],
    dimensions: [
      {
        id: "map",
        label: "map",
        table: "RosterVariant",
        column: "map",
        source: "base",
      },
      {
        id: "roster",
        label: "roster",
        table: "RosterVariant",
        column: "roster",
        source: "base",
      },
      {
        id: "is_best_for_map",
        label: "best for map",
        table: "RosterVariant",
        column: "is_best_for_map",
        source: "base",
      },
    ],
    filters: [
      {
        id: "map",
        label: "map",
        table: "RosterVariant",
        column: "map",
        source: "base",
        valueType: "text",
        operators: ["in", "nin"],
      },
      {
        id: "player",
        label: "player",
        table: "RosterVariant",
        column: "player",
        source: "base",
        valueType: "player",
        operators: ["in", "nin"],
      },
      {
        id: "is_best_for_map",
        label: "best for map",
        table: "RosterVariant",
        column: "is_best_for_map",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "yes", label: "yes" },
          { value: "no", label: "no" },
        ],
      },
    ],
  },
  ult_impact: {
    id: "ult_impact",
    label: "Ult impact",
    noun: "ult impact",
    description:
      "Fight win rate for hero ult usage scenarios: uncontested ults and mirrored ult trades.",
    table: "UltImpact",
    kind: "computed",
    sourceTables: ["PlayerStat", "Kill", "MercyRez", "UltimateStart"],
    grainNote:
      "One summary row per hero and ult-use scenario. The fight outcome and ult timing buckets reuse the same custom fight walk as the team ult-impact dashboard.",
    metrics: [
      {
        id: "win_rate",
        label: "win rate",
        description: "Weighted fight win rate (wins divided by fights × 100)",
        table: "UltImpact",
        column: "wins",
        source: "base",
        allowedAggs: ["ratio"],
        defaultAgg: "ratio",
        unit: "%",
        precision: 1,
        denominatorColumn: "fights",
        scale: 100,
      },
      {
        id: "fights",
        label: "fights",
        description: "Number of fights in the ult scenario",
        table: "UltImpact",
        column: "fights",
        source: "base",
        allowedAggs: ["sum", "avg", "max"],
        defaultAgg: "sum",
        precision: 0,
      },
      {
        id: "wins",
        label: "wins",
        description: "Number of fights won in the ult scenario",
        table: "UltImpact",
        column: "wins",
        source: "base",
        allowedAggs: ["sum", "avg", "max"],
        defaultAgg: "sum",
        precision: 0,
      },
      {
        id: "losses",
        label: "losses",
        description: "Number of fights lost in the ult scenario",
        table: "UltImpact",
        column: "losses",
        source: "base",
        allowedAggs: ["sum", "avg", "max"],
        defaultAgg: "sum",
        precision: 0,
        lowerIsBetter: true,
      },
    ],
    dimensions: [
      {
        id: "hero",
        label: "hero",
        table: "UltImpact",
        column: "hero",
        source: "base",
      },
      {
        id: "scenario",
        label: "scenario",
        table: "UltImpact",
        column: "scenario",
        source: "base",
      },
      {
        id: "side",
        label: "ult side",
        table: "UltImpact",
        column: "side",
        source: "base",
      },
      {
        id: "mirrored",
        label: "mirrored",
        table: "UltImpact",
        column: "mirrored",
        source: "base",
      },
      {
        id: "first_side",
        label: "first ult side",
        table: "UltImpact",
        column: "first_side",
        source: "base",
      },
    ],
    filters: [
      {
        id: "hero",
        label: "hero",
        table: "UltImpact",
        column: "hero",
        source: "base",
        valueType: "hero",
        operators: ["in", "nin"],
        enumOptions: HERO_OPTIONS,
      },
      {
        id: "scenario",
        label: "scenario",
        table: "UltImpact",
        column: "scenario",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "we used uncontested", label: "we used uncontested" },
          {
            value: "enemy used uncontested",
            label: "enemy used uncontested",
          },
          { value: "mirror, we first", label: "mirror, we first" },
          { value: "mirror, enemy first", label: "mirror, enemy first" },
        ],
      },
      {
        id: "side",
        label: "ult side",
        table: "UltImpact",
        column: "side",
        source: "base",
        valueType: "enum",
        operators: ["in", "nin"],
        enumOptions: [
          { value: "us", label: "us" },
          { value: "enemy", label: "enemy" },
          { value: "both", label: "both" },
        ],
      },
      {
        id: "mirrored",
        label: "mirrored",
        table: "UltImpact",
        column: "mirrored",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "yes", label: "yes" },
          { value: "no", label: "no" },
        ],
      },
      {
        id: "first_side",
        label: "first ult side",
        table: "UltImpact",
        column: "first_side",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "us", label: "us" },
          { value: "enemy", label: "enemy" },
        ],
      },
    ],
  },
  ult_usage: {
    id: "ult_usage",
    label: "Ult usage",
    noun: "ult usage",
    description:
      "Player ultimate usage, ults per map, and fight-opening ultimate heroes.",
    table: "UltUsage",
    kind: "computed",
    sourceTables: [
      "UltimateStart",
      "Kill",
      "MercyRez",
      "PlayerStat",
      "CalculatedStat",
    ],
    grainNote:
      "One summary row per player plus one row per fight-opening hero. The fight-opening counts and per-player rankings reuse the same ultimate usage analysis as the team dashboard.",
    metrics: [
      {
        id: "ults_used",
        label: "ults used",
        description: "Total ultimates used by the player summary row",
        table: "UltUsage",
        column: "ults_used",
        source: "base",
        allowedAggs: ["sum", "avg", "max"],
        defaultAgg: "sum",
        precision: 0,
      },
      {
        id: "maps_played",
        label: "maps played",
        description: "Maps represented by the summary row",
        table: "UltUsage",
        column: "maps_played",
        source: "base",
        allowedAggs: ["sum", "avg", "max"],
        defaultAgg: "sum",
        precision: 0,
      },
      {
        id: "ults_per_map",
        label: "ults per map",
        description: "Ultimate uses per map",
        table: "UltUsage",
        column: "ults_per_map",
        source: "base",
        allowedAggs: ["avg", "max", "min"],
        defaultAgg: "avg",
        precision: 2,
      },
      {
        id: "fight_openings",
        label: "fight openings",
        description: "Fights opened with an ultimate",
        table: "UltUsage",
        column: "fight_openings",
        source: "base",
        allowedAggs: ["sum", "avg", "max"],
        defaultAgg: "sum",
        precision: 0,
      },
    ],
    dimensions: [
      {
        id: "row_type",
        label: "summary type",
        table: "UltUsage",
        column: "row_type",
        source: "base",
      },
      {
        id: "player",
        label: "player",
        table: "UltUsage",
        column: "player",
        source: "base",
      },
      {
        id: "hero",
        label: "hero",
        table: "UltUsage",
        column: "hero",
        source: "base",
      },
      {
        id: "top_fight_opening_hero",
        label: "top fight-opening hero",
        table: "UltUsage",
        column: "top_fight_opening_hero",
        source: "base",
      },
    ],
    filters: [
      {
        id: "row_type",
        label: "summary type",
        table: "UltUsage",
        column: "row_type",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "player", label: "player" },
          {
            value: "fight opening hero",
            label: "fight opening hero",
          },
        ],
      },
      {
        id: "player",
        label: "player",
        table: "UltUsage",
        column: "player",
        source: "base",
        valueType: "player",
        operators: ["in", "nin"],
      },
      {
        id: "hero",
        label: "hero",
        table: "UltUsage",
        column: "hero",
        source: "base",
        valueType: "hero",
        operators: ["in", "nin"],
        enumOptions: HERO_OPTIONS,
      },
      {
        id: "top_fight_opening_hero",
        label: "top fight-opening hero",
        table: "UltUsage",
        column: "top_fight_opening_hero",
        source: "base",
        valueType: "hero",
        operators: ["in", "nin"],
        enumOptions: HERO_OPTIONS,
      },
    ],
  },
  trend: {
    id: "trend",
    label: "Trends",
    noun: "trend results",
    description:
      "Computed map results enriched with date, week, month, day-of-week, and recent-form buckets.",
    table: "TrendResult",
    kind: "computed",
    sourceTables: [
      "MatchStart",
      "RoundEnd",
      "ObjectiveCaptured",
      "PayloadProgress",
      "PointProgress",
      "PlayerStat",
      "Scrim",
    ],
    grainNote:
      "One row per map result, sorted from newest to oldest. Winners are computed with calculateWinner(), then rows are tagged with week/month/day and last-5/10/20 buckets for recent-form questions.",
    metrics: [
      {
        id: "win_rate",
        label: "win rate",
        description: "Share of maps won (avg of won × 100)",
        table: "TrendResult",
        column: "won",
        source: "base",
        allowedAggs: ["avg"],
        defaultAgg: "avg",
        unit: "%",
        precision: 1,
        scale: 100,
      },
      {
        id: "maps",
        label: "maps",
        description: "Number of maps",
        table: "TrendResult",
        column: null,
        source: "base",
        allowedAggs: ["count"],
        defaultAgg: "count",
        precision: 0,
      },
      {
        id: "wins",
        label: "wins",
        description: "Number of maps won",
        table: "TrendResult",
        column: "won",
        source: "base",
        allowedAggs: ["sum"],
        defaultAgg: "sum",
        precision: 0,
      },
      {
        id: "losses",
        label: "losses",
        description: "Number of maps lost",
        table: "TrendResult",
        column: "loss",
        source: "base",
        allowedAggs: ["sum"],
        defaultAgg: "sum",
        precision: 0,
        lowerIsBetter: true,
      },
    ],
    dimensions: [
      {
        id: "date",
        label: "date",
        table: "TrendResult",
        column: "date",
        source: "base",
      },
      {
        id: "week",
        label: "week",
        table: "TrendResult",
        column: "week",
        source: "base",
      },
      {
        id: "month",
        label: "month",
        table: "TrendResult",
        column: "month",
        source: "base",
      },
      {
        id: "day_of_week",
        label: "day of week",
        table: "TrendResult",
        column: "day_of_week",
        source: "base",
      },
      {
        id: "recent_bucket",
        label: "recent bucket",
        table: "TrendResult",
        column: "recent_bucket",
        source: "base",
      },
      {
        id: "result",
        label: "result",
        table: "TrendResult",
        column: "result",
        source: "base",
      },
      {
        id: "map",
        label: "map",
        table: "TrendResult",
        column: "map",
        source: "base",
      },
      {
        id: "scrim",
        label: "scrim",
        table: "TrendResult",
        column: "scrim",
        source: "base",
      },
    ],
    filters: [
      {
        id: "recent_bucket",
        label: "recent bucket",
        table: "TrendResult",
        column: "recent_bucket",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "last 5", label: "last 5" },
          { value: "last 10", label: "last 10" },
          { value: "last 20", label: "last 20" },
        ],
      },
      {
        id: "result",
        label: "result",
        table: "TrendResult",
        column: "result",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "win", label: "win" },
          { value: "loss", label: "loss" },
        ],
      },
      {
        id: "map",
        label: "map",
        table: "TrendResult",
        column: "map",
        source: "base",
        valueType: "text",
        operators: ["in", "nin"],
      },
      {
        id: "day_of_week",
        label: "day of week",
        table: "TrendResult",
        column: "day_of_week",
        source: "base",
        valueType: "enum",
        operators: ["in", "nin"],
        enumOptions: [
          "Sunday",
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday",
          "Saturday",
        ].map((day) => ({ value: day, label: day })),
      },
    ],
  },
  streak: {
    id: "streak",
    label: "Streaks",
    noun: "win/loss streaks",
    description:
      "Current and longest win/loss streaks computed from chronological map results.",
    table: "Streak",
    kind: "computed",
    sourceTables: [
      "MatchStart",
      "RoundEnd",
      "ObjectiveCaptured",
      "PayloadProgress",
      "PointProgress",
      "PlayerStat",
      "Scrim",
    ],
    grainNote:
      "One row for the current streak and one row each for the longest win and loss streak. Map winners come from the same calculateWinner()-based post-processing as trend results.",
    metrics: [
      {
        id: "length",
        label: "streak length",
        description: "Number of consecutive maps in the streak",
        table: "Streak",
        column: "length",
        source: "base",
        allowedAggs: ["max"],
        defaultAgg: "max",
        precision: 0,
      },
      {
        id: "streaks",
        label: "streaks",
        description: "Number of streak rows",
        table: "Streak",
        column: null,
        source: "base",
        allowedAggs: ["count"],
        defaultAgg: "count",
        precision: 0,
      },
    ],
    dimensions: [
      {
        id: "streak",
        label: "streak",
        table: "Streak",
        column: "streak",
        source: "base",
      },
      {
        id: "result",
        label: "result",
        table: "Streak",
        column: "result",
        source: "base",
      },
      {
        id: "start_date",
        label: "start date",
        table: "Streak",
        column: "start_date",
        source: "base",
      },
      {
        id: "end_date",
        label: "end date",
        table: "Streak",
        column: "end_date",
        source: "base",
      },
    ],
    filters: [
      {
        id: "streak",
        label: "streak",
        table: "Streak",
        column: "streak",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "current streak", label: "current streak" },
          { value: "longest win streak", label: "longest win streak" },
          { value: "longest loss streak", label: "longest loss streak" },
        ],
      },
      {
        id: "result",
        label: "result",
        table: "Streak",
        column: "result",
        source: "base",
        valueType: "enum",
        operators: ["eq", "neq"],
        enumOptions: [
          { value: "win", label: "win" },
          { value: "loss", label: "loss" },
          { value: "none", label: "none" },
        ],
      },
    ],
  },
};

export const DATASET_LIST = Object.values(DATASET_REGISTRY);

export function getDataset(id: DatasetId): DatasetDef {
  return DATASET_REGISTRY[id];
}

export function getMetric(
  dataset: DatasetId,
  id: string
): MetricDef | undefined {
  return DATASET_REGISTRY[dataset].metrics.find((m) => m.id === id);
}

export function getDimension(
  dataset: DatasetId,
  id: string
): DimensionDef | undefined {
  return DATASET_REGISTRY[dataset].dimensions.find((d) => d.id === id);
}

export function getFilter(
  dataset: DatasetId,
  id: string
): FilterDef | undefined {
  return DATASET_REGISTRY[dataset].filters.find((f) => f.id === id);
}

export const AGG_LABELS: Record<Aggregation, string> = {
  sum: "total",
  avg: "average",
  max: "max",
  min: "min",
  count: "count",
  per10: "per 10 min",
  ratio: "ratio",
};

/** Short SQL-flavoured rendering of an aggregation, for the technical layer. */
export const AGG_SQL_LABELS: Record<Aggregation, string> = {
  sum: "SUM",
  avg: "AVG",
  max: "MAX",
  min: "MIN",
  count: "COUNT",
  per10: "SUM/time×600",
  ratio: "SUM/SUM",
};
