import type { DatasetId } from "@/lib/query-builder/types";

export const DEFAULT_METRIC: Record<DatasetId, string> = {
  player_stat: "eliminations",
  calculated_stat: "mvp_score",
  kill: "kills",
  hero_swap: "swaps",
  ultimate: "ultimates",
  map: "maps",
  teamfight: "win_rate",
  opening_kill: "first_deaths",
  rotation_death: "rotation_deaths",
  map_result: "win_rate",
  team_performance: "win_rate",
  map_intelligence: "weighted_win_rate",
  player_map_performance: "win_rate",
  player_impact: "consistency_score",
  player_trend: "improvement_percentage",
  player_outlier: "abs_z_score",
  player_target: "progress_percent",
  role_performance: "win_rate",
  ult_economy: "win_rate",
  duel: "win_rate",
  ability_impact: "win_rate",
  ability_timing: "win_rate",
  swap_impact: "win_rate",
  hero_pool: "win_rate",
  hero_diversity: "diversity_score",
  hero_pickrate: "pick_rate",
  hero_trend: "playtime_trend",
  player_intelligence: "hero_pool_size",
  enemy_hero: "win_rate",
  ban_impact: "win_rate_delta",
  ult_combo: "win_rate",
  role_trio: "win_rate",
  roster_variant: "win_rate",
  ult_impact: "win_rate",
  ult_usage: "ults_used",
  trend: "win_rate",
  streak: "length",
};

export const DATASET_HINTS: Record<DatasetId, string[]> = {
  player_stat: [
    "player stat",
    "final blow",
    "final blows",
    "damage",
    "healing",
    "deaths",
    "time played",
    "playtime",
    "accuracy",
    "weapon accuracy",
    "critical hit accuracy",
    "scoped accuracy",
    "scoped critical hit accuracy",
    "environmental death",
    "environmental deaths",
    "best multikill",
    "biggest multikill",
    "multikill best",
    "widowmaker versus the time",
  ],
  calculated_stat: [
    "mvp",
    "map mvp",
    "map mvps",
    "fleta",
    "first pick percentage",
    "first pick rate",
    "first picks",
    "first death percentage",
    "first death rate",
    "first deaths",
    "duel winrate",
    "duel win rate",
    "ult charge time",
    "ultimate charge time",
    "time to use ult",
    "time to use ultimate",
    "drought time",
    "kills per ult",
    "kills per ultimate",
    "ajax",
    "ajaxes",
    "fight reversal percentage",
    "fight reversal rate",
  ],
  kill: [
    "kill feed",
    "kill event",
    "kill events",
    "kills by",
    "killed by",
    "critical kill",
    "critical kills",
    "environmental kill",
    "environmental kills",
    "killing blow",
    "kill damage",
    "victim",
    "victims",
  ],
  hero_swap: [
    "hero swap",
    "hero swaps",
    "swap event",
    "swap events",
    "swapped from",
    "swapped off",
    "swapped to",
    "swapped onto",
    "swap from",
    "swap off",
    "swap to",
    "swap onto",
    "time before swap",
  ],
  ultimate: [
    "ultimate event",
    "ultimate events",
    "ult event",
    "ult events",
    "ultimate used",
    "ultimates used",
    "ults used",
    "raw ult",
    "raw ults",
    "raw ultimate",
    "raw ultimates",
  ],
  ult_combo: [
    "ult combo",
    "ult combos",
    "ultimate combo",
    "ultimate combos",
    "combo win rate",
    "combo winrate",
    "counter ult",
    "counter ultimate",
    "respond to ult",
    "response ult",
  ],
  ult_impact: [
    "ult impact",
    "ultimate impact",
    "uncontested ult",
    "uncontested ultimate",
    "mirror ult",
    "mirror ultimate",
    "mirrored ult",
    "mirrored ultimate",
    "when we ult",
    "our ult win rate",
    "our ultimate win rate",
    "when we use ult",
    "when we use ultimate",
    "enemy ult win rate",
    "enemy ultimate win rate",
  ],
  ult_usage: [
    "ult usage",
    "ultimate usage",
    "ults per map",
    "ultimates per map",
    "ults per game",
    "ultimates per game",
    "ults per match",
    "ultimates per match",
    "most ults",
    "most ultimates",
    "fight opener",
    "fight openers",
    "open fights with ult",
    "opens fights with ult",
    "start fights with ult",
    "starts fights with ult",
    "opening ult",
    "opening ultimate",
    "fight openings per map",
    "fight openings per game",
    "fight openings per match",
    "opening ults per map",
  ],
  role_trio: [
    "role trio",
    "role trios",
    "lineup",
    "lineups",
    "comp",
    "comps",
    "composition",
    "compositions",
    "roster combo",
    "roster combos",
    "team comp",
    "team comps",
    "team composition",
    "team compositions",
    "player combination",
    "player combinations",
    "five stack",
    "starting five",
  ],
  roster_variant: [
    "roster",
    "rosters",
    "roster variant",
    "roster variants",
    "best roster",
    "best rosters",
    "best roster for each map",
    "best rosters by map",
    "best lineup for each map",
    "best lineups by map",
    "best comp for each map",
    "best comps by map",
    "best composition for each map",
    "best compositions by map",
    "map roster",
    "map rosters",
    "lineup by map",
    "lineups by map",
    "comp by map",
    "comps by map",
    "composition by map",
    "compositions by map",
  ],
  map: ["maps played", "opponent", "map count"],
  trend: [
    "trend",
    "trends",
    "over time",
    "recent form",
    "last 5 maps",
    "last 10 maps",
    "last 20 maps",
    "last 5 games",
    "last 10 games",
    "last 20 games",
    "last five",
    "last ten",
    "recent games",
    "weekly",
    "by week",
    "monthly",
    "by month",
    "day of week",
    "by day",
  ],
  streak: [
    "streak",
    "streaks",
    "win streak",
    "loss streak",
    "current streak",
    "current win streak",
    "current loss streak",
    "longest streak",
    "longest win streak",
    "longest loss streak",
  ],
  teamfight: [
    "fight",
    "teamfight",
    "team fight",
    "first pick",
    "first death",
    "dry fight",
    "wasted ult",
    "comeback",
    "comeback rate",
    "turn fight around",
    "turn fights around",
  ],
  opening_kill: [
    "opening kill",
    "opening kills",
    "opening pick",
    "opening picks",
    "opening death",
    "opening deaths",
    "first kill",
    "first kills",
    "dies first",
    "died first",
    "die first",
    "first to die",
    "gets first pick",
    "got first pick",
    "first picked",
    "picked first",
  ],
  rotation_death: [
    "rotation death",
    "rotation deaths",
    "rotational death",
    "rotational deaths",
    "caught rotating",
    "caught on rotation",
    "caught out",
    "caught out before fight",
    "caught out before fights",
    "picked while rotating",
    "picked on rotation",
    "picked before fight",
    "picked before fights",
    "died rotating",
    "dies rotating",
    "died before fight",
    "dies before fight",
    "pre fight death",
    "pre fight deaths",
    "pre-fight death",
    "pre-fight deaths",
    "die early",
    "dies early",
    "died early",
    "die early in fight",
    "die early in fights",
    "dies early in fight",
    "dies early in fights",
    "early fight death",
    "early fight deaths",
    "early death rate",
    "early deaths",
    "early death with low damage",
  ],
  map_result: [
    "best map mode",
    "best map type",
    "map duration",
    "map durations",
    "average map duration",
    "map playtime",
    "map time played",
    "maps played most",
    "most played maps",
    "played maps most",
    "map mode",
    "map modes",
    "map type",
    "map types",
    "map win",
    "map winrate",
    "map win rate",
    "record by map",
    "record against",
    "record versus",
    "map record",
    "match record",
  ],
  team_performance: [
    "team performance",
    "team stats",
    "team stat",
    "team aggregate",
    "team comparison",
    "our team",
    "opponent team",
    "enemy team",
    "us versus them",
    "us vs them",
    "we compared to them",
  ],
  map_intelligence: [
    "map intelligence",
    "weighted map win rate",
    "weighted win rate by map",
    "strength weighted",
    "time weighted",
    "time-decayed",
    "decayed win rate",
    "map trend",
    "map trends",
    "high confidence maps",
    "low confidence maps",
    "medium confidence maps",
    "insufficient confidence maps",
    "improving maps",
    "declining maps",
    "map type dependency",
    "map type dependencies",
    "best weighted maps",
    "worst weighted maps",
  ],
  player_map_performance: [
    "player map performance",
    "player map winrate",
    "player map win rate",
    "map performance",
    "players by map",
    "player by map",
    "best player on map",
    "best players on map",
    "perform best on",
    "performance on",
  ],
  player_impact: [
    "player impact",
    "impact metrics",
    "consistency",
    "consistent",
    "most consistent",
    "least consistent",
    "volatile",
    "volatility",
    "variance",
    "standard deviation",
    "stddev",
    "swingy",
    "streaky",
    "map mvp rate",
    "first picks per 10",
    "first deaths per 10",
    "ajax per 10",
    "all damage per 10",
    "damage taken per 10",
    "ultimates used per 10",
    "kills per ultimate",
    "kills per ult",
  ],
  player_trend: [
    "player trend",
    "player trends",
    "improving player",
    "improving players",
    "players improving",
    "player improving",
    "declining player",
    "declining players",
    "players declining",
    "player declining",
    "trending up",
    "trending down",
    "what is improving",
    "what are improving",
  ],
  player_outlier: [
    "outlier",
    "outliers",
    "z score",
    "z-score",
    "hero baseline",
    "baseline",
    "percentile",
    "far above",
    "far below",
    "above baseline",
    "below baseline",
  ],
  player_target: [
    "player target",
    "player targets",
    "player goal",
    "player goals",
    "target progress",
    "goal progress",
    "target change",
    "goal change",
    "progress toward target",
    "progress toward goal",
    "current value",
    "baseline value",
    "target value",
    "goal value",
    "scrim window",
    "target window",
    "on track",
    "off track",
    "stalled target",
    "saved target",
    "saved goal",
  ],
  role_performance: [
    "role performance",
    "role stats",
    "role stat",
    "role line",
    "role lines",
    "by role",
    "per role",
    "tank role",
    "damage role",
    "support role",
    "tank line",
    "damage line",
    "support line",
  ],
  ult_economy: [
    "ult economy",
    "ultimate economy",
    "ult advantage",
    "ult bank",
    "ult disadvantage",
    "ultimate disadvantage",
    "ult deficit",
    "ultimate deficit",
    "more ults",
    "more ultimates",
    "same ults",
    "same ultimates",
    "same number of ults",
    "same number of ultimates",
    "equal ults",
    "equal ultimates",
    "no ult advantage",
    "no ultimate advantage",
    "ahead an ult",
    "behind an ult",
  ],
  duel: ["duel", "duels", "matchup", "hero matchup", "enemy hero"],
  ability_impact: [
    "ability",
    "abilities",
    "cooldown",
    "used ability",
    "using ability",
    "suzu",
    "sleep dart",
    "biotic grenade",
    "teleporter",
    "amp it up",
    "lamp",
  ],
  ability_timing: [
    "ability timing",
    "cooldown timing",
    "when should",
    "when to use",
    "best phase",
    "phase timing",
    "pre fight",
    "pre-fight",
    "early fight",
    "mid fight",
    "late fight",
    "cleanup",
  ],
  swap_impact: [
    "swap impact",
    "swap winrate",
    "swap win rate",
    "when we swap",
    "when swapping",
    "swap count",
    "swaps per map",
    "too many swaps",
  ],
  hero_pool: [
    "hero pool",
    "hero winrate",
    "hero win rate",
    "hero winrates",
    "hero win rates",
    "hero wins",
    "hero losses",
    "top heroes",
    "best heroes",
    "most played hero",
    "most played heroes",
    "damage heroes",
    "support heroes",
    "tank heroes",
    "ultimate efficiency",
    "ult efficiency",
  ],
  hero_diversity: [
    "hero diversity",
    "hero pool diversity",
    "diverse hero pool",
    "diversity score",
    "unique heroes",
    "effective hero pool",
    "heroes per role",
    "role hero pool",
    "thin hero pool",
    "thinnest hero pool",
    "shared heroes",
    "specialist heroes",
  ],
  hero_pickrate: [
    "hero pickrate",
    "hero pick rate",
    "pickrate",
    "pick rate",
    "pick rates",
    "hero ownership",
    "ownership rate",
    "owns our",
    "owned by",
    "player hero share",
    "hero pool share",
  ],
  hero_trend: [
    "hero trend",
    "hero trends",
    "hero usage trend",
    "hero usage trends",
    "hero pick trend",
    "hero pick trends",
    "pick rate trend",
    "playtime trend",
    "trending hero",
    "trending heroes",
    "heroes trending",
    "hero meta",
    "meta trend",
  ],
  player_intelligence: [
    "player intelligence",
    "hero depth",
    "hero depths",
    "hero pool depth",
    "hero pool size",
    "deep hero pool",
    "deepest hero pool",
    "flexible",
    "flexibility",
    "one trick",
    "one-trick",
    "primary hero",
    "primary heroes",
    "best hero",
    "best heroes",
    "most played hero",
    "most played heroes",
    "primary time share",
    "hero dependency",
    "hero dependence",
    "forced off",
    "forced maps",
    "substitution rate",
    "forced substitution",
    "forced substitutions",
    "composite z score",
    "z score",
    "z-score",
  ],
  enemy_hero: [
    "against",
    "against enemy",
    "against enemy hero",
    "enemy heroes",
    "enemy hero win rate",
    "enemy hero winrate",
    "win rate against",
    "winrate against",
    "weak against",
    "worst against",
    "best against",
  ],
  ban_impact: [
    "ban",
    "bans",
    "banned",
    "hero ban",
    "ban impact",
    "ban rate",
    "most banned",
    "weak point",
    "weak points",
    "strong ban",
    "strong bans",
  ],
};

export const METRIC_ALIASES: Record<string, string[]> = {
  final_blows: ["final blow", "final blows", "finals"],
  eliminations: ["eliminations", "elims"],
  deaths: ["deaths", "deaths per 10"],
  assists: ["assists", "offensive assists"],
  mvp_score: ["mvp", "mvp score", "average mvp score"],
  map_mvp_count: ["map mvps", "map mvp count"],
  fleta_deadlift: ["fleta", "fleta deadlift", "deadlift"],
  first_pick_pct: [
    "first pick",
    "first pick percentage",
    "first pick rate",
    "opening pick rate",
  ],
  first_pick_count: ["first picks", "first pick count", "opening picks"],
  first_pick_percentage: [
    "first pick",
    "first pick percentage",
    "first pick rate",
    "opening pick rate",
  ],
  first_death_pct: [
    "first death",
    "first death percentage",
    "first death rate",
    "opening death rate",
  ],
  first_death_count: ["first deaths", "first death count", "opening deaths"],
  first_death_percentage: [
    "first death",
    "first death percentage",
    "first death rate",
    "opening death rate",
  ],
  kill_time: [
    "opening kill time",
    "average opening kill time",
    "opening kill timing",
  ],
  fight_time: [
    "time into fight",
    "average time into fight",
    "opening pick timing",
    "opening kill fight timing",
  ],
  ajax_count: ["ajax", "ajaxes", "ajax count"],
  ult_charge_time: [
    "ult charge time",
    "ultimate charge time",
    "average ult charge time",
    "average ultimate charge time",
    "charge ult",
    "charges ult",
    "charged ult",
    "charge ultimate",
    "charges ultimate",
    "charged ultimate",
  ],
  average_ult_charge_time: [
    "ult charge time",
    "ultimate charge time",
    "average ult charge time",
    "average ultimate charge time",
    "charge ult",
    "charges ult",
    "charged ult",
    "charge ultimate",
    "charges ultimate",
    "charged ultimate",
  ],
  time_to_use_ult: [
    "time to use ult",
    "time to use ultimate",
    "average time to use ult",
    "average time to use ultimate",
  ],
  average_time_to_use_ult: [
    "time to use ult",
    "time to use ultimate",
    "average time to use ult",
    "average time to use ultimate",
    "use ult",
    "use ultimate",
  ],
  drought_time: ["drought time", "average drought time"],
  average_drought_time: ["drought time", "average drought time"],
  kills_per_ult: [
    "kills per ult",
    "kills per ultimate",
    "elims per ult",
    "eliminations per ultimate",
  ],
  kills_per_ultimate: [
    "kills per ult",
    "kills per ultimate",
    "elims per ult",
    "eliminations per ultimate",
  ],
  duel_winrate: ["duel winrate", "duel win rate", "duel rate"],
  duel_winrate_percentage: ["duel winrate", "duel win rate", "duel rate"],
  fight_reversal: [
    "fight reversal",
    "fight reversal percentage",
    "fight reversal rate",
    "fight comeback",
    "fight comeback rate",
    "comeback rate",
    "comeback percentage",
  ],
  time_played: ["time played", "playtime", "played it", "played them"],
  hero_time_played: ["time played", "playtime", "hero time played"],
  hero_damage: ["hero damage", "damage dealt", "damage per 10"],
  all_damage: ["all damage", "total damage"],
  damage_taken: ["damage taken", "damage taken per 10"],
  healing: ["healing", "heals", "healing per 10"],
  environmental_deaths: [
    "environmental death",
    "environmental deaths",
    "boop deaths",
    "booped deaths",
  ],
  kills: ["kills", "kill count", "kill events"],
  critical_kills: ["critical kill", "critical kills", "headshot kills"],
  environmental_kills: [
    "environmental kill",
    "environmental kills",
    "boop kills",
    "booped kills",
  ],
  kill_damage: [
    "kill damage",
    "killing blow damage",
    "average kill damage",
    "average killing blow damage",
  ],
  swaps: ["swaps", "hero swaps", "swap events"],
  time_before_swap: [
    "time before swap",
    "time before swapping",
    "average time before swap",
    "average time before swapping",
  ],
  ultimates: [
    "ultimates",
    "ultimates used",
    "ults",
    "ults used",
    "ultimate events",
    "ult events",
  ],
  multikill_best: ["best multikill", "biggest multikill", "multikill best"],
  ults_used: [
    "ults used",
    "ultimates used",
    "ultimate usage",
    "most ults",
    "most ultimates",
    "total ultimates",
  ],
  ultimates_used: ["ults used", "ultimates used", "ultimate usage"],
  ultimates_earned: ["ults earned", "ultimates earned"],
  weapon_accuracy: ["weapon accuracy", "shot accuracy"],
  critical_hit_accuracy: [
    "critical hit accuracy",
    "crit accuracy",
    "critical accuracy",
  ],
  scoped_accuracy: ["scoped accuracy", "scope accuracy", "scoped acc"],
  scoped_critical_hit_accuracy: [
    "scoped critical hit accuracy",
    "scoped crit accuracy",
    "scoped critical accuracy",
  ],
  ult_efficiency: [
    "ultimate efficiency",
    "ult efficiency",
    "eliminations per ultimate",
    "elims per ult",
  ],
  kd: ["kd", "k d", "final blows per death"],
  diversity_score: ["diversity", "diversity score", "hero diversity"],
  role_coverage: ["role coverage", "coverage"],
  unique_heroes: ["unique heroes", "hero count", "heroes per role"],
  effective_hero_pool: ["effective hero pool", "effective heroes"],
  average_maps_per_hero: ["average maps per hero", "maps per hero"],
  specialist_heroes: ["specialist heroes", "one player heroes"],
  shared_heroes: ["shared heroes", "shared hero pool"],
  pick_rate: ["pickrate", "pick rate", "pick rates", "hero pool share"],
  ownership_rate: [
    "ownership",
    "ownership rate",
    "owns",
    "owned by",
    "share of hero",
  ],
  hero_pool_size: [
    "hero pool size",
    "hero depth",
    "hero depths",
    "hero pool depth",
    "deep hero pool",
    "deepest hero pool",
    "flexibility",
    "flexible",
  ],
  primary_time_share: [
    "primary time share",
    "primary share",
    "most played share",
    "one trick",
    "one-trick",
    "hero dependency",
    "hero dependence",
    "dependent",
  ],
  substitution_rate: [
    "substitution rate",
    "forced off",
    "forced substitution",
    "forced substitutions",
  ],
  maps_forced: ["forced maps", "maps forced", "forced off maps"],
  primary_secondary_delta: [
    "primary secondary delta",
    "primary-secondary delta",
    "secondary delta",
    "hero depth delta",
  ],
  composite_z_score: [
    "composite z score",
    "composite z-score",
    "z score",
    "z-score",
    "hero score",
    "best hero",
    "best heroes",
  ],
  ban_rate: ["ban rate", "banned rate", "most banned"],
  maps_banned: ["maps banned", "bans", "ban count", "total bans"],
  win_rate_delta: [
    "delta",
    "win rate delta",
    "winrate delta",
    "difference",
    "deviation",
    "impact",
    "weak point",
    "weak points",
    "strong ban",
    "strong bans",
  ],
  win_rate_with: ["win rate with ban", "winrate with ban"],
  win_rate_without: ["win rate without ban", "winrate without ban"],
  overall_win_rate: ["overall win rate", "overall winrate", "baseline"],
  uses: [
    "uses",
    "used",
    "usage",
    "how often",
    "most common",
    "combo count",
    "response count",
  ],
  games: ["games", "maps", "maps played", "sample", "sample size"],
  playtime: [
    "playtime",
    "time played",
    "map playtime",
    "map time played",
    "map duration",
    "map durations",
    "average map duration",
    "most played",
    "most time",
    "played most",
    "played the most",
  ],
  ults_per_map: [
    "ults per map",
    "ultimates per map",
    "ults per game",
    "ultimates per game",
    "ults per match",
    "ultimates per match",
  ],
  fight_openings: [
    "fight openings",
    "fight opener",
    "fight openers",
    "open fights",
    "opens fights",
    "start fights",
    "starts fights",
    "open fights with ult",
    "opens fights with ult",
    "start fights with ult",
    "starts fights with ult",
    "opening ult",
    "opening ultimate",
  ],
  fight_openings_per_map: [
    "fight openings per map",
    "fight openings per game",
    "fight openings per match",
    "fight opener per map",
    "fight opener per game",
    "fight opener per match",
    "fight openers per map",
    "fight openers per game",
    "fight openers per match",
    "opening ults per map",
    "opening ults per game",
    "opening ults per match",
    "opening ultimates per map",
    "opening ultimates per game",
    "opening ultimates per match",
    "open fights with ult per map",
    "open fights with ult per game",
    "open fights with ult per match",
  ],
  avg_wasted_ults: ["wasted ult", "wasted ults", "wasted ultimates"],
  avg_swaps: [
    "avg swaps",
    "average swaps",
    "swaps per map",
    "average swaps per map",
  ],
  first_pick_rate: ["first pick rate", "first-pick rate", "opening pick rate"],
  first_death_rate: [
    "first death rate",
    "first-death rate",
    "opening death rate",
  ],
  first_ult_rate: ["first ult rate", "first ultimate rate"],
  dry_fight_rate: ["dry fight rate", "dry-fight rate"],
  reversal_rate: [
    "reversal rate",
    "fight reversal rate",
    "comeback rate",
    "comeback win rate",
    "turnaround rate",
  ],
  dry_fight_reversal_rate: [
    "dry fight reversal rate",
    "dry-fight reversal rate",
    "dry reversal rate",
    "dry fight comeback rate",
    "dry comeback rate",
  ],
  non_dry_fight_reversal_rate: [
    "non dry fight reversal rate",
    "non-dry fight reversal rate",
    "non dry reversal rate",
    "non dry fight comeback rate",
    "non-dry fight comeback rate",
    "non dry comeback rate",
  ],
  ultimate_efficiency: [
    "ultimate efficiency",
    "ult efficiency",
    "fight wins per ultimate",
    "fight wins per ult",
  ],
  avg_ults_per_non_dry_fight: [
    "average ults per non dry fight",
    "average ultimates per non dry fight",
    "ults per non dry fight",
    "ultimates per non dry fight",
  ],
  avg_ults_in_won_fights: [
    "average ults in won fights",
    "average ultimates in won fights",
    "ults in won fights",
  ],
  avg_ults_in_lost_fights: [
    "average ults in lost fights",
    "average ultimates in lost fights",
    "ults in lost fights",
  ],
  avg_advantage: [
    "average ult advantage",
    "avg ult advantage",
    "average ultimate advantage",
    "avg ultimate advantage",
    "average ult bank",
    "ult bank advantage",
  ],
  first_events: ["opening kill", "opening kills", "first kill", "first kills"],
  first_deaths: [
    "first death",
    "first deaths",
    "opening death",
    "opening deaths",
    "dies first",
    "died first",
    "die first",
    "first to die",
    "picked first",
    "first picked",
  ],
  first_picks: [
    "first pick",
    "first picks",
    "opening pick",
    "opening picks",
    "opening kills secured",
    "gets first pick",
    "got first pick",
  ],
  losses: ["losses", "lost", "lose"],
  duels: ["duels", "duel count", "duel sample"],
  rotation_deaths: [
    "rotation death",
    "rotation deaths",
    "rotational death",
    "rotational deaths",
    "caught rotating",
    "caught out",
    "caught-out death",
    "caught-out deaths",
    "picked while rotating",
    "picked on rotation",
    "picked before fight",
    "picked before fights",
    "pre fight death",
    "pre fight deaths",
    "pre-fight death",
    "pre-fight deaths",
  ],
  rotation_death_rate: [
    "rotation death rate",
    "rotation deaths rate",
    "rotational death rate",
    "rotation rate",
    "caught out rate",
    "caught-out death rate",
    "caught out death rate",
  ],
  early_death_rate: [
    "early death rate",
    "early fight death rate",
    "pre fight death rate",
    "pre-fight death rate",
    "die early",
    "dies early",
    "died early",
    "die early in fights",
    "dies early in fights",
    "early deaths",
    "early fight deaths",
  ],
  pre_fight_damage: [
    "pre fight damage",
    "pre-fight damage",
    "average pre fight damage",
    "average pre-fight damage",
  ],
  kill_distance: [
    "kill distance",
    "death distance",
    "average kill distance",
    "average death distance",
  ],
  final_blows_per10: ["final blows per 10", "finals per 10"],
  eliminations_per10: ["eliminations per 10", "elims per 10", "kills per 10"],
  hero_damage_per10: [
    "hero damage per 10",
    "damage per 10",
    "damage dealt per 10",
  ],
  deaths_per10: ["deaths per 10", "deaths per 10 minutes"],
  all_damage_per10: [
    "all damage per 10",
    "total damage per 10",
    "all damage per 10 minutes",
  ],
  damage_taken_per10: ["damage taken per 10", "damage taken per 10 minutes"],
  healing_per10: ["healing per 10", "healing per 10 minutes"],
  healing_received_per10: ["healing received per 10", "heals received per 10"],
  assists_per10: ["assists per 10", "offensive assists per 10"],
  solo_kills_per10: ["solo kills per 10", "solo kill per 10"],
  objective_kills_per10: ["objective kills per 10", "objective kill per 10"],
  offensive_assists_per10: [
    "offensive assists per 10",
    "offensive assist per 10",
  ],
  defensive_assists_per10: [
    "defensive assists per 10",
    "defensive assist per 10",
  ],
  ults_earned_per10: [
    "ults earned per 10",
    "ultimates earned per 10",
    "ult charge per 10",
  ],
  ults_used_per10: [
    "ults used per 10",
    "ultimates used per 10",
    "ult usage per 10",
  ],
  first_picks_per10: [
    "first picks per 10",
    "opening picks per 10",
    "first pick count per 10",
  ],
  first_deaths_per10: [
    "first deaths per 10",
    "opening deaths per 10",
    "first death count per 10",
  ],
  ajax_per10: ["ajax per 10", "ajaxes per 10", "ajax count per 10"],
  damage_per10: [
    "damage per 10",
    "hero damage per 10",
    "damage per 10 minutes",
  ],
  win_rate: ["winrate", "winrates", "win rate", "win rates", "wr"],
  weighted_win_rate: [
    "weighted win rate",
    "time weighted win rate",
    "time-decayed win rate",
    "decayed win rate",
    "strength weighted",
  ],
  recent_win_rate: ["recent win rate", "recent form", "last 10 win rate"],
  trend_delta: ["trend delta", "recent delta", "change", "improvement"],
  playtime_trend: ["playtime trend", "usage trend", "hero usage trend"],
  pick_rate_trend: ["pick rate trend", "pickrate trend", "pick trend"],
  improvement_percentage: [
    "improvement percentage",
    "improvement %",
    "change percentage",
    "trend percentage",
  ],
  improvement: ["improvement", "trend change"],
  raw_change: ["raw change", "late minus early"],
  early_value: ["early value", "early sample", "first half"],
  late_value: ["late value", "late sample", "second half"],
  abs_z_score: [
    "outlier",
    "outliers",
    "absolute z score",
    "absolute z-score",
    "distance from baseline",
  ],
  z_score: ["z score", "z-score", "above baseline", "below baseline"],
  percentile: ["percentile", "hero percentile"],
  per10_value: ["per 10 value", "actual per 10"],
  baseline_per10: ["baseline", "baseline per 10", "hero baseline"],
  progress_percent: ["progress", "progress percentage", "progress %"],
  current_value: ["current value", "current stat", "current"],
  baseline_value: ["baseline value", "baseline"],
  target_value: ["target value", "goal value"],
  gap_to_target: ["gap to target", "remaining", "distance to target"],
  target_percent: [
    "target percent",
    "target percentage",
    "target change",
    "target change percent",
    "target change percentage",
    "goal change",
    "goal change percent",
    "goal change percentage",
  ],
  sample_scrims: ["sample scrims", "scrim sample"],
  consistency_score: [
    "consistency",
    "consistent",
    "consistency score",
    "steady",
    "stable",
    "stability",
    "stable output",
  ],
  eliminations_per10_stddev: [
    "eliminations volatility",
    "elims volatility",
    "eliminations standard deviation",
  ],
  deaths_per10_stddev: ["deaths volatility", "deaths standard deviation"],
  all_damage_per10_stddev: [
    "damage volatility",
    "damage standard deviation",
    "volatile damage",
  ],
  healing_per10_stddev: [
    "healing volatility",
    "healing standard deviation",
    "volatile healing",
  ],
  map_mvp_rate: ["map mvp rate", "map mvp percentage"],
  fleta_deadlift_percentage: ["fleta deadlift", "fleta deadlift percentage"],
  fight_reversal_percentage: [
    "fight reversal",
    "fight reversal percentage",
    "fight reversal rate",
    "fight comeback",
    "fight comeback rate",
    "comeback rate",
    "comeback percentage",
  ],
  length: ["length", "streak length", "streak count"],
  fights: ["fights", "teamfights", "team fights"],
  duration: [
    "duration",
    "fight duration",
    "teamfight duration",
    "team fight duration",
    "average fight length",
    "average fight duration",
    "fight length",
  ],
  maps: ["maps", "map count", "maps played"],
};

export const DIMENSION_ALIASES: Record<string, string[]> = {
  player: ["player", "who"],
  hero: ["hero"],
  our_hero: ["our hero", "hero"],
  enemy_hero: ["enemy hero", "opponent hero"],
  attacker_hero: ["attacker hero", "killing hero"],
  victim_hero: ["victim hero", "death hero"],
  map: ["map", "maps"],
  map_type: ["map type", "mode"],
  opponent: ["opponent", "opponents"],
  scrim: ["scrim", "scrims"],
  date: ["date"],
  week: ["week", "weekly"],
  month: ["month", "monthly"],
  day_of_week: ["day", "day of week"],
  recent_bucket: ["recent bucket", "recent form"],
  result: ["result", "win loss"],
  dry_fight: ["dry fight"],
  first_pick: ["first pick"],
  first_death: ["first death"],
  first_ult: ["first ult", "first ultimate"],
  advantage_bucket: ["advantage bucket", "ult advantage"],
  ability: ["ability", "cooldown"],
  phase: ["phase", "timing", "fight phase"],
  impact_rating: ["impact rating", "impact"],
  side: ["side", "team"],
  death_type: ["death type", "rotation death"],
  attacker: ["attacker", "killer"],
  victim: ["victim", "killed player"],
  attacker_side: ["attacker side", "killer side"],
  type: ["type"],
  combo: ["combo", "ult combo", "ultimate combo"],
  roster: ["roster", "lineup", "comp", "composition"],
  hero_a: ["first hero"],
  hero_b: ["second hero"],
  response_hero: ["response hero", "counter hero"],
  trio: [
    "lineup",
    "comp",
    "composition",
    "role trio",
    "roster combo",
    "player combination",
  ],
  tank: ["tank"],
  dps1: ["damage 1", "dps 1"],
  dps2: ["damage 2", "dps 2"],
  support1: ["support 1"],
  support2: ["support 2"],
  used: ["used", "usage"],
  scenario: ["scenario", "used vs not used"],
  mirrored: ["mirrored", "mirror ult", "mirror ultimate"],
  first_side: ["first ult side", "first ultimate side"],
  row_type: ["summary type"],
  top_fight_opening_hero: ["top fight-opening hero", "fight opener"],
  role: ["role"],
  primary_hero: ["primary hero", "best hero"],
  most_played_hero: ["most played hero"],
  is_primary: ["is primary", "primary"],
  is_most_played: ["is most played", "most played"],
  had_swap: ["had swap", "with swaps", "without swaps"],
  swap_count: ["swap count", "number of swaps"],
  swap_count_bucket: ["swap count bucket", "swaps"],
  first_swap_timing: ["first swap timing", "swap timing"],
  streak: ["streak"],
  trend: ["trend"],
  direction: ["direction"],
  trending: ["trending"],
  status: ["status", "target status", "goal status"],
  confidence: ["confidence", "sample confidence"],
  start_date: ["start date", "started"],
  end_date: ["end date", "ended"],
};
