#!/usr/bin/env bun
import { writeFileSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";
import { luminance, renderHalftoneSvg, sampleDots } from "../src/lib/halftone";

// Tuning dials — adjust against the figure, then re-run.
const COLS = 58; // dot columns across the cropped figure
const CELL = 10; // SVG units between dot centers
const MAX_RADIUS = 0.95; // fraction of half-cell
const THRESHOLD = 0.7; // luminance >= this is background when sampling dots
const BBOX_THRESHOLD = 0.45; // stricter: only near-black figure pixels set the crop
const PAD = 0.06; // padding around the figure bbox, as a fraction of bbox size
const MARGIN = 0.02; // edge band (fraction of each dimension) excluded from the figure search
const GATE_FLOOR = 10; // min dark px in a row/col before it counts; guards near-blank images

// Run from the repo root: `bun scripts/generate-halftone.ts`.
const root = process.cwd();
const SRC = path.join(root, "public/falling.png");
const OUT = path.join(root, "src/app/falling-halftone.ts");

// Composite any alpha over white so the background is uniform before sampling.
const base = sharp(SRC).flatten({ background: "#ffffff" });
const { data, info } = await base
  .clone()
  .raw()
  .toBuffer({ resolveWithObject: true });
const { width, height, channels } = info;

// Pass 1: find the figure's bounding box via row/column projection. The source
// has a lot of near-white margin AND sparse edge noise (e.g. a 1px-wide dark
// column at x=0 spanning the full height). A raw min/max bbox gets dragged to
// the whole frame by that noise, so instead we count near-black pixels per row
// and per column and keep only the dense band where the actual figure lives.
const colDark = new Array<number>(width).fill(0);
const rowDark = new Array<number>(height).fill(0);
for (let y = 0; y < height; y++) {
  for (let x = 0; x < width; x++) {
    const i = (y * width + x) * channels;
    if (luminance(data[i], data[i + 1], data[i + 2]) >= BBOX_THRESHOLD)
      continue;
    colDark[x]++;
    rowDark[y]++;
  }
}

// Search only the interior, ignoring a thin border margin where edge artifacts
// (like the full-height 1px column at x=0) live. A row/column belongs to the
// figure only if its dark-pixel count clears a gate relative to the densest
// interior line — this rejects sparse noise.
const mx = Math.round(width * MARGIN);
const my = Math.round(height * MARGIN);
const interiorMax = (counts: number[], lo: number, hi: number) => {
  let m = 0;
  for (let k = lo; k <= hi; k++) if (counts[k] > m) m = counts[k];
  return m;
};
const colGate = Math.max(
  GATE_FLOOR,
  interiorMax(colDark, mx, width - 1 - mx) * 0.1
);
const rowGate = Math.max(
  GATE_FLOOR,
  interiorMax(rowDark, my, height - 1 - my) * 0.1
);
const firstAbove = (counts: number[], gate: number, lo: number, hi: number) => {
  for (let k = lo; k <= hi; k++) if (counts[k] >= gate) return k;
  return -1;
};
const lastAbove = (counts: number[], gate: number, lo: number, hi: number) => {
  for (let k = hi; k >= lo; k--) if (counts[k] >= gate) return k;
  return -1;
};
const minX = firstAbove(colDark, colGate, mx, width - 1 - mx);
const maxX = lastAbove(colDark, colGate, mx, width - 1 - mx);
const minY = firstAbove(rowDark, rowGate, my, height - 1 - my);
const maxY = lastAbove(rowDark, rowGate, my, height - 1 - my);
// maxX/maxY cannot be -1 once minX/minY >= 0 (same range, same gate), so
// checking the mins is sufficient to detect "no figure found".
if (minX < 0 || minY < 0) {
  throw new Error("No figure found — check BBOX_THRESHOLD against the source.");
}

const padX = Math.round((maxX - minX) * PAD);
const padY = Math.round((maxY - minY) * PAD);
const left = Math.max(0, minX - padX);
const top = Math.max(0, minY - padY);
// If the figure sits within padX/padY of the margin, `left`/`top` clamp to 0
// and the eaten padding spills to the opposite edge. Fine for a centered
// figure; revisit if a future source hugs an edge.
const cropW = Math.min(width - left, maxX - minX + 1 + padX * 2);
const cropH = Math.min(height - top, maxY - minY + 1 + padY * 2);

// Pass 2: sample the cropped figure into halftone dots.
const cropped = await sharp(SRC)
  .flatten({ background: "#ffffff" })
  .extract({ left, top, width: cropW, height: cropH })
  .raw()
  .toBuffer({ resolveWithObject: true });

const dots = sampleDots(
  cropped.data,
  cropped.info.width,
  cropped.info.height,
  cropped.info.channels,
  { cols: COLS, cell: CELL, maxRadius: MAX_RADIUS, threshold: THRESHOLD }
);

const svg = renderHalftoneSvg(dots);

const module = `// GENERATED by scripts/generate-halftone.ts — do not edit by hand.
// Source: public/falling.png. Re-run: bun scripts/generate-halftone.ts
export const fallingHalftoneSvg = ${JSON.stringify(svg)};
`;

writeFileSync(OUT, module);
console.log(
  `Wrote ${OUT} — ${dots.length} dots, ${svg.length} bytes ` +
    `(crop ${cropW}x${cropH} from ${width}x${height})`
);
