-- CreateEnum
CREATE TYPE "public"."Title" AS ENUM ('DEVELOPER', 'EMPLOYEE', 'BETA_TESTER', 'DAY_ONE_USER', 'BASIC_PLAN_SUBSCRIBER', 'PREMIUM_PLAN_SUBSCRIBER', 'VIP', 'HIGHEST_RANK_ON_A_HERO', 'HIGHEST_AJAX_COUNT', 'HIGHEST_FLETA_DEADLIFT_PERCENTAGE', 'TOP_3_KILLS', 'TOP_3_DAMAGE_DEALT', 'TOP_3_HEALING', 'TOP_3_DAMAGE_BLOCKED', 'TOP_3_DEATHS', 'TOP_3_TIME_PLAYED');

-- AlterTable
ALTER TABLE "public"."User" ADD COLUMN     "bannerImage" TEXT,
ADD COLUMN     "titles" "public"."Title"[] DEFAULT ARRAY[]::"public"."Title"[];
